### ISSUE TITLE
How does this differ from Expo?

### ISSUE THREAD

**Issue by corysimmons** [nandorojo/solito#1]
Sorry, Discussions aren't enabled for this repo, but I'm super interested in your stack.

**Comment by nandorojo** [comment]
this isn’t released yet, but it’ll work with expo. it’s a middleware between expo and next, and a set of suggestions to work with both.

to learn more, see this discussion: https://github.com/axeldelafosse/expo-next-monorepo-example/pull/1

**Comment by corysimmons** [comment]
Thanks for the quick reply. Love your work!
