### ISSUE TITLE
Get current route path

### ISSUE THREAD

**Issue by jhbarnett** [nandorojo/solito#10]
How would you advise reading the path for the current route? Before `useParams` was introduced, I targeted NextJS and React Navigation router events to parse both query params and path. But now monitoring the router events feels like overkill. 

Have I overlooked a way to access this information already in Solito? If not, would you be inclined to include it?

**Comment by nandorojo** [comment]
Could you clarify what you mean? Are you trying to read in the `asPath`?

**Comment by jhbarnett** [comment]
Yes, reading in the value of `asPath` is exactly what I'm looking for. 

To help clarify, here's the current implementation I'm reworking now that `useParams` is available.

```
# index.tsx

navigation.addListener('state', ({ data: { state } }) => {
    if (state) {
      const getPathFromState = (params: any): string => {
        return 'path' in params && !!params.path
          ? params.path
          : getPathFromState(params.params)
      }
      const currentRoute = state.routes[state.index]
      const url = getPathFromState(currentRoute.params)
      const urlParts = parseUrlPath(url)
      setRoute(urlParts.path, urlParts.params)
    }
  })
```

```
# index.web.tsx
router.events.on('routeChangeComplete', (url) => {
    const urlParts = parseUrlPath(url)
    setRoute(urlParts.path, urlParts.params)
  })
```

**Comment by nandorojo** [comment]
for the second one, couldn’t you just use `Router.asPath`?

**Comment by nandorojo** [comment]
Maybe we could have a `useAsPath()` hook. I’m just not sure how reliable `getPathFromStatw(navigation.getState())` is for reading in a path. Maybe it’s fine though, I’d have to do some testing

**Comment by jhbarnett** [comment]
`useAsPath()` would be perfect for my use case. 

In a monorepo structured similarly to the example you've included, I'm trying to avoid direct imports of platform specific dependencies like `next/router` and `@react-navigation/native` in the `/app` package. Solito has made this possible for every other aspect of navigation which is why I think something like `useAsPath()` has a place in the Solito API. I understand your hesitation however and there is a clear workaround with `Router.asPath` and `getPathFromState(navigation.getState())`. 

Your work with Solito and various talks on Expo + Next.js have been immensely helpful for me and my team. Thank you. Don't hesitate to reach out if you're in need of help or feedback at any point.

**Comment by nandorojo** [comment]
I’m a bit hesitant to release this hook officially, since it’s prone to user error. Maybe we could just make it here for use in user land.

**Comment by jhbarnett** [comment]
Makes sense, I'm also now realizing [`getPathFromState`](https://github.com/react-navigation/react-navigation/blob/main/packages/core/src/getPathFromState.tsx) builds the path according to screen names, not linking config. Whereas there is an accurate path attribute in the route params that's seemingly undocumented.

```
import { getPathFromState } from '@react-navigation/native'

const getPathFromStateParams = (params: any): string => {
  return 'path' in params && !!params.path
    ? params.path
    : getPathFromStateParams(params.params)
}

getPathFromStateParams(state.routes[state.index].params) === "/acme-corp/leaderboard"
getPathFromState(state) === "/App/Group/Leaderboard"
```

**Comment by nandorojo** [comment]
Yeah, I've seen the `path` field. This is why I'm hesitant to expose/document this feature. It's too dependent on changing React Navigation internals. Out of curiosity, when do you need this feature on Native? Is it for sharing a given screen or something?

**Comment by nandorojo** [comment]
I think a better solution would be to open an issue/discussion on React Navigation, asking for the best way to get the current `path` on a given screen. If they give a documented solution, then I'd add it here.
