### ISSUE TITLE
useParam not working as expected on first render

### ISSUE THREAD

**Issue by gabrielEloy** [nandorojo/solito#100]
When using the useParam hook to retrieve URL params during the application's first render, the value returned by the hook is undefined

for instance, given we insert the URL:

`http://localhost:3000/example-route?query=test+my+friend`

the following snippet

```javascript
const Example = () => {
const [query, setQuery] = useParam("query");

useEffect(() => {
console.log({query});
}, []);

return (<View><Text>test component</Text></View>)
}
```

the consoled value will be:

<img width="158" alt="image" src="https://user-images.githubusercontent.com/37480915/177408069-69f97e9f-19e1-4ade-b431-2f541c366ad2.png">

**Comment by nandorojo** [comment]
i believe this is known behavior from useRouter() from Next.js, presumably to have the same props on the client/server and avoid hydration issues of static rendering. at least that’s my best guess

**Comment by nandorojo** [comment]
i think it has the right parameter on first render for dynamic parameters, right? `/artists/[slug]` should have `slug` on the first render i think

**Comment by nandorojo** [comment]
To get around this, you probably need to use Next.js' `getServerSideProps` to enable dynamic SSR. Otherwise, this is working the same way that Next.js' router would.
