### ISSUE TITLE
Can't resolve react-native

### ISSUE THREAD

**Issue by KaniDev** [nandorojo/solito#103]
Hello ! I am trying to implement Solito in a Next + React Native monorepo (no Expo)

I built the repo myself since the solito starter was using Expo; everything works seemingly fine. 
However, after adding Solito and its config as the website says, I have an error at runtime when starting Next: `error - ../../node_modules/@react-navigation/native/lib/module/Link.js:2:0
Module not found: Can't resolve 'react-native'`

The file exists and isn't empty.

Import trace:
```
../../node_modules/@react-navigation/native/lib/module/index.js
../../node_modules/solito/build/router/use-link-to.js
../../node_modules/solito/build/link/core.js
../../node_modules/solito/build/link/index.js
../../node_modules/solito/link/index.js
../shared/homepage.tsx
./pages/index.tsx
```

[next.config.txt](https://github.com/nandorojo/solito/files/9072773/next.config.txt)

**Comment by nandorojo** [comment]
It's hard to help here. Monorepos are very complicated and there are many things that could be wrong with how you set it up. I recommend using the starter monorepo, and just uninstall `expo` from `apps/expo` (and you can rename that folder too).

```sh
npx create-solito-app@latest my-solito-app
cd my-solito-app/apps/expo
yarn remove expo
```
