### ISSUE TITLE
Motilink sometimes doesn't work on android

### ISSUE THREAD

**Issue by arjendevos** [nandorojo/solito#108]
When using MotiLink in a list, it doesn't always navigate.

We have a MotiLink like this:
```
<MotiLink href={`/product-detail/${product.id}`}
        animate={React.useMemo(
          () =>
            ({ hovered, pressed }) => {
              "worklet";

              return {
                backgroundColor: hovered || pressed ? "#EDEDED" : "#fff",
              };
            },
          []
        )}>{children}</MotiLink>
```

We use them in a list and whenever we press on an item we should expect to go to another page. Sometimes it works and we navigate to another page but a lot of times i only see the hover effect and it doesn't navigate.

**Comment by nandorojo** [comment]
oh android, I see. when you say sometimes — does it work sometimes?

**Comment by nandorojo** [comment]
also, are you on the latest version of moti?

**Comment by arjendevos** [comment]
Yes it works sometimes. I'm using "canary"
