### ISSUE TITLE
Error when running create-solito-app

### ISSUE THREAD

**Issue by dannyhw** [nandorojo/solito#11]
Hey I love this, great work! 

As mentioned on twitter I got an error running create-solito-app. Setting up with vercel got me a 404 though that could easily be a me problem since I've not used it before.

``` 
npx create-solito-app@latest my-solito-app
npx: installed 82 in 10.733s
yarn run v1.23.0-20211220.1904
error Couldn't find a package.json file in "/Users/danny/workspace/solito"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command failed: yarn ts-node index.ts
```

running 
```
macos 12.2.1
node v14.19.0
yarn 1.23.0-20211220.1904
``` 

let me know if you need any more details.

**Comment by nandorojo** [comment]
should be fixed with https://github.com/nandorojo/solito/commit/d39d3b3608cabfa2a31a02b208c21f1e99e8ccf1

thanks for finding that!

**Comment by dannyhw** [comment]
No worries thanks for the quick response! Trying it now :)

**Comment by dannyhw** [comment]
@nandorojo getting a different error 😅 

```
[solito] Failed to download example

 Error: Cannot find module '/Users/danny/.npm/_npx/21214/lib/node_modules/create-solito-app/dist/package.json' 
```

**Comment by nandorojo** [comment]
ah yeah I see the issue.

I'm not a node CLI developer often, so I forget that running the CLI from `npx` isn't the same as on my computer lol.

I think I am pushing a fix now

**Comment by nandorojo** [comment]
FWIW, even though it errors, it actually is working. it's just failing to edit your `package.json` with the proper name.

I'm not sure how to solve this. I'm using `process.cwd()` to get the current place where the user is located, but that doesn't seem to be working.

**Comment by dannyhw** [comment]
ah I see so this require is throwing the exception?
```
const pkg = require(path.resolve(
      process.cwd(),
      resolvedProjectPath,
      'package.json'
    ))
```

**Comment by nandorojo** [comment]
yeah that's the line. I'm playing with it now too. it seems to keep reading from `.npx` instead of cwd. i'm going to try printing some stuff out to see what's up

**Comment by nandorojo** [comment]
maybe path.resolve is unnecessary there since it's already resolved? hm

**Comment by dannyhw** [comment]
well I think even if it is usually resolve is pretty smart and can remove extra things. Seems possible that npx might change the way process.cwd works though. There is probably a good example of this I can check in the storybook repo.

**Comment by nandorojo** [comment]
<img width="772" alt="Screen Shot 2022-03-14 at 6 54 48 PM" src="https://user-images.githubusercontent.com/13172299/158273993-ff27027e-06fb-497a-8c2c-ec00e9859075.png">

I'm going a bit crazy here. Shouldn't these log the same things, but one of them just has `package.json` appended to it? Because they're logging totally different things. `resolvedPackagePath` is correct, and somehow `pkgPath` is giving me something in the wrong directory

**Comment by dannyhw** [comment]
Ah ok well I guess path.resolve tries to be clever since it wants to resolve a absolute path, you can use join to just put them together.

**Comment by nandorojo** [comment]
right...I tried `join` as well, weirdly that gives me the same error.

something feels so off. this code:

```ts
    console.log('[solito] resolved path :', resolvedProjectPath)
    const pkgPath = resolvedProjectPath + '/package.json'
    console.log('[solito] package.json path:', pkgPath)
```

Results in this error:

```sh
[solito] resolved path : /path-to/create-solito-app/create-test-app
[solito] package.json path: /path-to/create-solito-app/dist/package.json
```

I replaced my actual paths with `path-to`. How can this make any sense?

**Comment by nandorojo** [comment]
If I do this:

```ts
    const pkgPath = `${resolvedProjectPath}/package.json`
```

It gives the wrong path. But if I take out `/package.json` at the end, it gives the right one. It's as if the variable is getting hoisted early and cached or something.

**Comment by nandorojo** [comment]
Yeah that's gotta be it. When I use `ts-node` it seems to work.

**Comment by dannyhw** [comment]
wow this is really weird, is there a chance it could be related to the spawning of a child process?

**Comment by dannyhw** [comment]
if you emit js from tsc and run that instead of ts-node does it work?

**Comment by nandorojo** [comment]
I'll try that too. Have to go to dinner so I'm going to publish this without the editing of package.json for now so it doesn't have any substantial errors. Who knew CLI and FS was so complicated lol

**Comment by nandorojo** [comment]
Okay so it works for me now.

The only weird thing left is, when I deploy to Vercel, it doesn't work, but building locally does work. 🧐

**Comment by nandorojo** [comment]
fixed
