### ISSUE TITLE
Loading Custom Icon Font

### ISSUE THREAD

**Issue by neilgamb** [nandorojo/solito#116]
I have been able to successfully load custom google fonts into my Solito app so I think I'm close on this.  Thanks in advance.

I am following the [Expo docs to load a custom icon font via IcoMoon](https://docs.expo.dev/guides/icons/#createiconsetfromicomoon).  Loading fine on native / expo but it seems Next is unable to locate the font file.  I believe I have my next-fonts config set up correctly, because as I said, normal fonts are loading fine.  But I also know that on web, custom fonts are being loaded by the <link> tag in the document head.  So not sure how a static asset like local .tff file gets loaded....

 Please see below for relative code:

`next.config.js`
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack5: true
}

const { withExpo } = require('@expo/next-adapter')
const withPlugins = require('next-compose-plugins')
const withImages = require('next-images')
const withFonts = require('next-fonts')
const withTM = require('next-transpile-modules')([
  'solito',
  'dripsy',
  '@dripsy/core',
  'moti',
  '@motify/core',
  '@motify/components',
  'app'
])

module.exports = withPlugins(
  [
    withTM,
    withFonts,
    [
      withImages,
      {
        images: {
          disableStaticImages: true
        }
      }
    ],
    [withExpo, { projectRoot: __dirname }]
  ],
  nextConfig
)

```

`useResouces.ts`
```
import * as Font from 'expo-font'
import { useEffect, useState } from 'react'

export const useResources = () => {
  const [fontsLoaded, setFontsLoaded] = useState(false)
  const [iconsLoaded, setIconsLoaded] = useState(false)

  const loadFontAsync = async () => {
    try {
      await Font.loadAsync({
        RobotoSlab: require('../assets/fonts/RobotoSlab-Regular.ttf'),
        OpenSans: require('../assets/fonts/OpenSans-Regular.ttf'),
        'OpenSans-Bold': require('../assets/fonts/OpenSans-SemiBold.ttf')
      })
    } catch (error) {
      //   console.log('Font Load Error:', error)
    } finally {
      setFontsLoaded(true)
    }
  }

  const loadIconsAsync = async () => {
    try {
      await Font.loadAsync({
        IcoMoonFont: require('../assets/icons/icomoonFont.ttf')
      })
    } catch (error) {
      // console.log('Icon Font Load Error:', error)
    } finally {
      setIconsLoaded(true)
    }
  }

  useEffect(() => {
    loadFontAsync()
    loadIconsAsync()
  }, [])

  return {
    fontsLoaded,
    iconsLoaded
  }
}
```

`dripsy.tsx`
```
import * as Font from 'expo-font'
import { useEffect, useState } from 'react'

export const useResources = () => {
  const [fontsLoaded, setFontsLoaded] = useState(false)
  const [iconsLoaded, setIconsLoaded] = useState(false)

  const loadFontAsync = async () => {
    try {
      await Font.loadAsync({
        RobotoSlab: require('../assets/fonts/RobotoSlab-Regular.ttf'),
        OpenSans: require('../assets/fonts/OpenSans-Regular.ttf'),
        'OpenSans-Bold': require('../assets/fonts/OpenSans-SemiBold.ttf')
      })
    } catch (error) {
      //   console.log('Font Load Error:', error)
    } finally {
      setFontsLoaded(true)
    }
  }

  const loadIconsAsync = async () => {
    try {
      await Font.loadAsync({
        IcoMoonFont: require('../assets/icons/icomoonFont.ttf')
      })
    } catch (error) {
      // console.log('Icon Font Load Error:', error)
    } finally {
      setIconsLoaded(true)
    }
  }

  useEffect(() => {
    loadFontAsync()
    loadIconsAsync()
  }, [])

  return {
    fontsLoaded,
    iconsLoaded
  }
}
```

`Icon.tsx`
```
import { createIconSetFromIcoMoon } from '@expo/vector-icons'

import icoMoonConfig from '../assets/icons/icoMoonConfig.json'

const Icon = createIconSetFromIcoMoon(
  icoMoonConfig,
  'IcoMoonFont',
  'iconmoonFont.ttf'
)

export default Icon
```

and finally an instance of icon:
`<Icon name="add" color="blue" size={50} />`

RESULT:

![native](https://user-images.githubusercontent.com/26474370/181118473-097b4128-e994-4488-8002-6da8268366b0.jpeg)
<img width="1840" alt="web" src="https://user-images.githubusercontent.com/26474370/181118517-b1722bc6-8329-42df-9843-12fd84e8beff.png">

**Comment by neilgamb** [comment]
ok major :face_palm::skin-tone-2:

I just needed to add the .tff into the `public` dir of the next project....

**Comment by neilgamb** [comment]
I'm actually going to re-open this because I noticed that if I navigate to another screen within my nextJS app, and reload, the font file is not loaded correctly, so this leaves me to believe I still have some work to be done with the nextjs config as it relates to loading my custom .tff file....

`Failed to decode downloaded font: http://localhost:3000/home/icoMoonFont.ttf`

**Comment by nandorojo** [comment]
are you using next-font

**Comment by neilgamb** [comment]
yes — i'm using `"next-fonts": "^1.5.1",` please see the next.config.js file that I posted. does that look correct?

**Comment by neilgamb** [comment]
This screen recording may be helpful...

https://user-images.githubusercontent.com/26474370/181127898-21f5aed3-ba0c-47ff-884a-c75e9cdd79c0.mov

**Comment by AndyZZH** [comment]
Don't know much about next-font. But here is my setup for get expo vector icon working next. Hope it helps.

```
/** @type {import('next').NextConfig} */

const path = require('path')

const nextConfig = {
  reactStrictMode: true,
  webpack5: true,
  webpack: (config, options) => {
    config.module.rules.push({
      test: /\.ttf$/,
      loader: "url-loader", // or directly file-loader
      include: path.resolve(__dirname, "../../node_modules/@expo/vector-icons"),
    })
    return config
  }
}

const { withExpo } = require('@expo/next-adapter')
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')([
  'solito',
  'dripsy',
  '@dripsy/core',
  'moti',
  '@motify/core',
  '@motify/components',
  'app',
])

module.exports = withPlugins(
  [withTM, [withExpo, { projectRoot: __dirname }]],
  nextConfig
)
```

**Comment by neilgamb** [comment]
Great, thank you.  I wound up using a script to generate all icons into .tsx components using `react-native-svg`.... i will definitely book mark this if and when we need to change the approach.

**Comment by nandorojo** [comment]
i commented on your PR with the proper approach, which is to use `next-fonts`.

Example: https://moti.fyi/next

**Comment by neilgamb** [comment]
I tried configuring my next app with `next-fonts` and had no luck.  I posted all the relevant config code in the original comment above if you want to take a look and see if there is something I did wrong?

**Comment by neilgamb** [comment]
By the way, thanks for the great work on this stack!  Really enjoying it and especially the Dx so far 👏

**Comment by nandorojo** [comment]
looks right to me…what if you move your `images` key into `nextConfig`?

**Comment by nandorojo** [comment]
i’m using next 12.1.0 btw and it’s all working there for me
