### ISSUE TITLE
[suggestion] Add a gitignore file to the blank project

### ISSUE THREAD

**Issue by dannyhw** [nandorojo/solito#12]
When setting up the blank project via vercel I got a project without a .gitignore it would be cool to have one ready to go.

Happy to help add it if you're interested in it :)

I'm guessing that just copying the one from the root of this repo would work

**Comment by nandorojo** [comment]
ah good call! mind adding that?

**Comment by nandorojo** [comment]
fixed https://github.com/nandorojo/solito/commit/656e892992fe7a96882ef5fb654bb90d863d89f7

**Comment by dannyhw** [comment]
damn that was quick haha 🏃
