### ISSUE TITLE
image is not showing on browser

### ISSUE THREAD

**Issue by vnaeimabadi** [nandorojo/solito#121]
I add import { Image } from 'dripsy' for showing image

<Image
          sx={{
            height: 86,
            aspectRatio: 2,
            ml: 10,
          }}
          resizeMode="contain"
          source={{
            uri: 'http://vasfa.ir/wp-content/uploads/2020/03/Vasfa-Logo.png',
          }}
        />
        
but after deployment on Vercel the image is not showing.

this is web link:
https://vasfa.vercel.app

**Comment by vnaeimabadi** [comment]
this works properly on local
https://user-images.githubusercontent.com/14070643/183421181-bb4298ec-3943-45e7-82fa-81c082cab68a.mp4

but when deploy it on Vercel it won't work properly

https://user-images.githubusercontent.com/14070643/183422135-535c9fad-4759-4d0c-81a8-c0302843a1a0.mp4

**Comment by nandorojo** [comment]
did you install next-image

**Comment by vnaeimabadi** [comment]
I am using 
`import { Image } from 'dripsy' `
for showing image

**Comment by vnaeimabadi** [comment]
this is the repo

**Comment by vnaeimabadi** [comment]
@nandorojo 
any update?

**Comment by nandorojo** [comment]
i am helping for free, please don't ping issues

**Comment by nandorojo** [comment]
@vnaeimabadi did you end up solving this?

**Comment by nandorojo** [comment]
Closing for now, but let me know if the problem persists.

**Comment by vnaeimabadi** [comment]
it was about blocking the link of the image from the hosting server.
I fix that by changing that link.
thanks

**Comment by nandorojo** [comment]
I'm excited to share the new Solito image component: https://solito.dev/usage/image
