### ISSUE TITLE
useRouter's back doesn't work in stack screen?

### ISSUE THREAD

**Issue by levelingup** [nandorojo/solito#123]
Hi, not sure if this is the right place to ask for issues. I've tried to use the back feature from `useRouter()`, but it doesn't do anything on the iOS simulator.

I was able to navigate from SearchResultsScreen to DetailScreen, but when I click on the back, it doesn't do anything.

```export function NativeNavigation() {
  const {back} = useRouter();
  return (
    <Stack.Navigator>
      <Stack.Screen
        name="results"
        component={SearchResultsScreen}
        options={{
          title: 'Results',
        }}
      />
      <Stack.Screen
        name="details"
        component={DetailScreen}
        options={{
          title: '',
          headerTransparent: true,
          headerLeft: () => (
            <TouchableOpacity onPress={() => back()}>
              <Ionicons name="chevron-back-outline" size={35} />
            </TouchableOpacity>
          )
        }}
      />
    </Stack.Navigator>
  )
}
```

**Comment by nandorojo** [comment]
this is because you’re calling `useRouter` outside of the navigator context. you should abstract yourself header left button into its own component to make this work.

**Comment by nandorojo** [comment]
alternatively, `options` can be a function which takes `({ navigation })` as an argument, and you can call `navigate.goBack` there

**Comment by sleekLancelot** [comment]
Hi, I was just going to open an issue about this. I use a mono-repo and although going to previous route with `    const { back } = useRouter()
...
back()
` works like it should on web, on my expo app it takes me to the initial-Route.

**Comment by nandorojo** [comment]
please see my answer

**Comment by levelingup** [comment]
Hi @nandorojo thanks for the quick reply and your help!

I was able to get it working when I use `options` as a function:

```
        options= {({navigation}) => ({
          title: '',
          headerTransparent: true,
          headerLeft: () => (
            <TouchableOpacity onPress={() => navigation.goBack()}>
              <Ionicons name="chevron-back-outline" size={35} />
            </TouchableOpacity>
          )
        })}
```
I also tried the other option, creating its own component, which I think I rather do to keep my codebase cleaner. I did what you suggested but still wasn't able to get it working:

`/navigation/native/index.tsx`

```
export function NativeNavigation() {
  return (
    <Stack.Navigator>

      // ....

      <Stack.Screen
        name="details"
        component={DetailScreen}
        options={{
          title: '',
          headerTransparent: true,
          headerLeft: () => (
            <BackButton />
          )
        }}
      />

     // ...

    </Stack.Navigator>
  )
}
```
I created its own `<BackButton />` component:

```
import React from "react";
import { TouchableOpacity } from "react-native";
import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'solito/router'

const BackButton = () => {
    const {back} = useRouter();
    return (
        <TouchableOpacity onPress={() => back()}>
            <Ionicons name="chevron-back-outline" size={35} />
        </TouchableOpacity>
    )
}

export default BackButton;
```

Did I do something wrong here?

Thanks!

**Comment by nandorojo** [comment]
hmm i'm surprised that the back button one didn't work. i'll take a look when i have some time

**Comment by sleekLancelot** [comment]
Incase anyone needs help with this, similar to the problem @levingup has except mine kept going back to the initialRouteName in the expo app.
I solved this by setting the 'backBehavior' in the DrawerNavigator options to 'history'.
`
        <Drawer.Navigator
          initialRouteName='SomeScreen'
          backBehavior='history'
          >
            .....
         </Drawer.Navigator>
`

**Comment by nandorojo** [comment]
Can you try on the latest version?

```sh
yarn add solito@canary
```
