### ISSUE TITLE
Support react-navigation on web platform

### ISSUE THREAD

**Issue by clayrisser** [nandorojo/solito#127]
I am trying to use solito in expo web. It seems that it is trying to use the nextjs routing logic, but it should be using the react-navigation logic when using expo on web.

**Comment by nandorojo** [comment]
Solito's purpose is to tie this altogether with Next.js. If you aren't using Next.js, you won't get value from Solito. You can just use React Navigation directly across both Web and Native.

**Comment by nandorojo** [comment]
For reference, you can use the `Link`, `useLinkTo` hooks from React Navigation directly if you're maintaining consistency with URLs.
