### ISSUE TITLE
Dripsy Custom Fonts working on Expo, but not Next

### ISSUE THREAD

**Issue by dijour** [nandorojo/solito#130]
Hi there, thanks for putting this project together. It's so cool. This is probably a better question for the Dripsy GitHub package, but since this is in the context of the Solito monorepo I figured I'd ask here.

Here's what the project structure looks like (see image below). I created 2 font folders in `packages/app/provider` and I'm importing them into `packages/app/provider/fonts.tsx`. This `<Fonts>` provider wraps the Expo app and works fine, and I followed the `dripsy.tsx` setup for using 2 custom fonts. It's definitely working, because I see both custom fonts rendering in the Expo app. The imported fonts are all OTF.

![image](https://user-images.githubusercontent.com/26984516/187078379-8851675a-f111-417d-8a2b-8269de040300.png)

The Next app is giving me some trouble, however. I know that the `<Fonts>` provider is an Expo-only provider, so it can't be used here. I imported the fonts from the /public folder into the Head of `_app.tsx` in the Next app, and I know they're being imported because Chrome Dev Tools shows a half dozen fonts in the **Sources** tab. When I inspect the rendered text using this Font Finder tool (https://add0n.com/font-finder.html), the font being rendered is "Times". So it's not even trying to render the right font.

![image](https://user-images.githubusercontent.com/26984516/187078874-04084f79-4119-4dfb-bd4e-22b6eb4d869c.png)
 
@nandorojo might you know what I'm doing wrong? Would love some assistance.

**Comment by nandorojo** [comment]
you need to add font face CSS to the website too, i think that may be the missing piece in the docs

**Comment by dijour** [comment]
Hmm. @nandorojo maybe there's an additional piece missing here, but I imported the globals.css file into `_app.tsx` and no change. The font names I declared are identical to the ones defined in `dripsy.tsx`. 
![image](https://user-images.githubusercontent.com/26984516/187083968-b2dd62b9-e7f3-40a6-9e68-24daa7e7c90a.png)


On a separate note, the Dripsy docs say that the font imports in `<Link>` tags should be done in `_document.tsx`, but since that file seems to be using a default export from your custom Expo / Next Adapter, I'm not sure I can make the `<Head>` import there. So I did it in `_app.tsx`. 

Let me know what you think, perhaps there's something else I'm missing.

![image](https://user-images.githubusercontent.com/26984516/187083921-312f9ac6-ce44-43b7-bd4e-7d2de903fd42.png)

**Comment by nandorojo** [comment]
What if you made your `font-face` `src` use the absolute url `(/fonts/...)` instead of using `../public/`?

**Comment by dijour** [comment]
I’ve tried that too, neither one works. In VS code I can cmd+click on both URL paths and they open the fonts correctly. So the URLs work. Not sure what else the issue could be. I’ll keep digging.

Dean Z. Dijour
Dijour Ventures, LLC.
(732) 832-5281

**Comment by nandorojo** [comment]
Did you try inspecting the browser dev tools and seeing what the URLs point to in your CSS?

**Comment by dijour** [comment]
Browser inspector is pointing to correct URL in the source tree (it even renders fonts in the preview)
<img width="601" alt="image" src="https://user-images.githubusercontent.com/26984516/187313531-0ba8489c-cf8f-4ef8-af85-f680f251b1a0.png">

Style tag added to `_app.tsx` is definitely being applied, as I set all Body text to blue, but the font-family (line 76 in screenshot) did not get applied. You can see I made 2 simple Divs in the page, and the inspector shows them inheriting the Body font-family, but they are still rendering "Times".

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/26984516/187314506-6eaef8e0-2005-4843-a012-366d4dbdf48c.png">

Thanks for your patience in investigating this. Might you have a sample Solito repo where you import 1 or 2 custom fonts into Dripsy / Next / Expo? It would be pretty useful to see how you structure it. No pressure though, I appreciate your help nonetheless.

**Comment by nandorojo** [comment]
Just added an example monorepo which uses custom fonts. I managed to get `Inter` working properly here on both the app and website.

[Here is the code.](https://github.com/nandorojo/solito/tree/master/example-monorepos/with-custom-font)

You can try it with this script:

```sh
npx create-solito-app@latest my-solito-app -t with-custom-font
```

And here is the result:

<img width="1879" alt="Screen Shot 2022-08-29 at 7 36 48 PM" src="https://user-images.githubusercontent.com/13172299/187316988-22f04dcd-4d63-41bc-a131-dca48cf48142.png">

**Comment by nandorojo** [comment]
btw, your `<link href="/font/...." />` should have a leading `/`

**Comment by dijour** [comment]
Wow! Thank you for this :) 

I got everything up and running. Issue resolved. You rock!!
