### ISSUE TITLE
Is there an option to disable scroll for nextjs?

### ISSUE THREAD

**Issue by arjendevos** [nandorojo/solito#133]
I want this option in MotiLink:

`<Link href="/other-page" scroll={false}></Link>`

**Comment by nandorojo** [comment]
this isn’t currently implemented, but I would accept a PR!

**Comment by arjendevos** [comment]
I don't understand this:
`export type LinkCoreProps = {
  children: React.ReactNode
} & Omit<ComponentProps<typeof NextLink>, 'passHref'>`

This would mean we get all the props of NextLink right?

**Comment by arjendevos** [comment]
So like this? https://github.com/nandorojo/solito/pull/134

**Comment by nandorojo** [comment]
Yeah, but you need the `MotiLink` to pass down this option too.

**Comment by nandorojo** [comment]
Actually, never mind, that should be fine.
