### ISSUE TITLE
Tailwind `plugin` is declared but not used. Is it expected?

### ISSUE THREAD

**Issue by wzulfikar** [nandorojo/solito#146]
In tailwind starter, the `apps/next/tailwind.config.js` has a `plugin` variable (L1) that's not used. What does it supposed to do?

https://github.com/nandorojo/solito/blob/d9d5361acd7107c65f8ff409c4dbcf1f6dd3fa73/example-monorepos/with-tailwind/apps/next/tailwind.config.js#L1-L16

**Comment by nandorojo** [comment]
@marklawlor?

**Comment by marklawlor** [comment]
This is actually a small bug, fix is here https://github.com/nandorojo/solito/pull/149.The plugin adds some additional Tailwind features like [Platform Variants](https://www.nativewind.dev/core-concepts/platforms). This isn't documented very well on the site, there's an open issue to track the documentation

If you do you not to use these features your safe to simply remove the plugin.
