### ISSUE TITLE
useParam doesn't return expected value

### ISSUE THREAD

**Issue by hlynurstef** [nandorojo/solito#152]
I just updated to v.1.0.10 and I noticed that `useParam` is not giving me the expected value in React Native when I use the following code:

Login screen that calls `router.push`:

```typescript
import { useRouter } from "solito/router";

export const LoginScreen: React.FC => {
  const router = useRouter();
  
  const signIn = useCallback(async () => {
    router.push(`/home/foobar`);
  }, [router]);


  return <Button onPress={signIn}>Login</Button>;
}
```

Home screen that gets id using `useParam`:
```typescript
import { createParam } from "solito";

const { useParam } = createParam<{ id: string }>();

export const HomeScreen: React.FC => {
  const [id] = useParam("id");

  return <Text>{`User ID: ${id}`}</Text>
}
```

![solito](https://user-images.githubusercontent.com/15615089/189552528-e279447f-869a-47cc-989f-25726c02395f.png)

In version `0.0.29` `useParam` returns `"foobar"`
In version `1.0.10` `useParam` returns `{id: "foobar"}`

Is this expected or a bug? I couldn't find any reference to changes to the API in the release notes or in the docs.

**Comment by nandorojo** [comment]
Oh wow, that’s not good. I’m pushing a fix now. Sorry about that.

**Comment by nandorojo** [comment]
Should be fixed in 1.0.11. Can you let me know?

**Comment by hlynurstef** [comment]
Confirmed fixed in v.1.0.11, thanks for the quick fix!

![solito2](https://user-images.githubusercontent.com/15615089/189553024-9506b406-99dc-409e-a19d-1eece8f6e143.png)

**Comment by nandorojo** [comment]
great!
