### ISSUE TITLE
Moti in solito 1.0.11

### ISSUE THREAD

**Issue by karmatradeDev** [nandorojo/solito#154]
Hi i'm not sure if its me but ive tried pretty much everything on my end.

moti doesn't seem to be included in the new solito 1.0.11 release

when I download the zip file its there, and on github its there, but when I delete my yarn.lock and update solito and install moti is not present in the solito node_modules.

<img width="252" alt="Screen Shot 2022-09-12 at 1 56 31 PM" src="https://user-images.githubusercontent.com/86848104/189741092-d4cca6d6-bcda-4969-a5bd-00011d3c5c7c.png">
<img width="915" alt="Screen Shot 2022-09-12 at 2 35 29 PM" src="https://user-images.githubusercontent.com/86848104/189741095-3ccc496d-a447-4863-8818-468e7bd3a9b0.png">
<img width="641" alt="Screen Shot 2022-09-12 at 2 38 55 PM" src="https://user-images.githubusercontent.com/86848104/189741097-d932419c-1d64-434f-ad89-70612bbc420c.png">

**Comment by nandorojo** [comment]
Just pushed a fix. Can you try 1.0.12?
