### ISSUE TITLE
Dripsy in the useful libraries section links to an email marketing company

### ISSUE THREAD

**Issue by SleeplessByte** [nandorojo/solito#16]
https://solito.dev/resources#useful-libraries

The dripsy link redirects to https://www.prospectpro.com/. I don't think that's intended.

**Comment by nandorojo** [comment]
Hm that's so odd lol I'll fix

**Comment by nandorojo** [comment]
had dripsy.com instead of dripsy.xyz by accident. good catch @SleeplessByte!
