### ISSUE TITLE
useParam initial value doesn't work on native

### ISSUE THREAD

**Issue by louisholley** [nandorojo/solito#172]
hey

doing `const [thing, setThing] = useParam('myParam', { initial: 'whatever' })` doesn't seem to work on native - `thing` is always undefined if not explicitly passed. am i missing something or will we need to build a workaround for this?

**Comment by nandorojo** [comment]
Yeah this field only applies on Web, since the user might override the field in the URL bar. You can instead do `[thing = ‘whatever]` if you want. In hindsight I think my API could be better.

**Comment by louisholley** [comment]
nice - we may be using the field incorrectly in that case. that's a good shout though, thanks @nandorojo
