### ISSUE TITLE
Navigating Recursively Not Supported?

### ISSUE THREAD

**Issue by kevinvangelder** [nandorojo/solito#174]
I have a dynamic route `/:username`. On mobile, if I navigate from `/user1` to `/some-other-page` and link to `/user2`, rather than pushing a copy of that page with the new username parameter it navigates back to the previous page with the old username parameter. Is there some option or setting we need to enable in order to utilize recursive navigation?

**Comment by nandorojo** [comment]
can you try adding `getId` to your `<Screen />`?

```tsx
<Screen 
  name="user"
  getId={({ params }) => params?.username}
/>
```

**Comment by kevinvangelder** [comment]
@nandorojo That worked, thanks! Did I miss this somewhere in the documentation? If not, it would be great if it could be added.

**Comment by nandorojo** [comment]
Check out React Navigation docs for most configuration on the native side: https://reactnavigation.org/docs/screen/#getid

**Comment by kevinvangelder** [comment]
Okay, that's useful, but as someone who's been using React Navigation for years I've never needed that prop until using React Navigation + Solito, so it would have been helpful to me to have had this linked from the Dynamic Route section in the documentation.

Thanks again!

**Comment by nandorojo** [comment]
yeah that’s a good place to document it, I’m open to a PR

**Comment by kevinvangelder** [comment]
PR: https://github.com/nandorojo/solito/pull/176
