### ISSUE TITLE
 Server Error ReferenceError: React is not defined

### ISSUE THREAD

**Issue by ydrea** [nandorojo/solito#179]
The  following error appears whenever I edit the '/next/pages/user/_app.tsx'.
Undoing the changes doesn't resolve it :(

```
error - pages/_app.tsx (16:2) @ MyApp
error - ReferenceError: React is not defined
    at MyApp (webpack-internal:///./pages/_app.tsx:10:163)
    at renderWithHooks (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
    at renderIndeterminateComponent (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
    at renderElement (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
    at renderNodeDestructive (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
    at renderNode (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6009:12)
    at renderChildrenArray (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5965:7)
    at renderNodeDestructive (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5897:7)
    at renderElement (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5761:9)
    at renderNodeDestructive (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11) {
  page: '/'
}
  14 |   var Component = _ref.Component,
  15 |       pageProps = _ref.pageProps;
> 16 |   return React.createElement(React.Fragment, null, React.createElement(Head, null), React.createElement(Provider, null, React.createElement(Component, pageProps)));
     |  ^
  17 | }
  18 | 
  19 | export default MyApp;
```

**Comment by xinha-sh** [comment]
> The following error appears whenever I edit the '/next/pages/user/_app.tsx'. Undoing the changes doesn't resolve it :(
> 
> ```
> error - pages/_app.tsx (16:2) @ MyApp
> error - ReferenceError: React is not defined
>     at MyApp (webpack-internal:///./pages/_app.tsx:10:163)
>     at renderWithHooks (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5448:16)
>     at renderIndeterminateComponent (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5521:15)
>     at renderElement (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5736:7)
>     at renderNodeDestructive (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11)
>     at renderNode (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6009:12)
>     at renderChildrenArray (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5965:7)
>     at renderNodeDestructive (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5897:7)
>     at renderElement (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5761:9)
>     at renderNodeDestructive (/home/ydrea/white-tree/solito/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5875:11) {
>   page: '/'
> }
>   14 |   var Component = _ref.Component,
>   15 |       pageProps = _ref.pageProps;
> > 16 |   return React.createElement(React.Fragment, null, React.createElement(Head, null), React.createElement(Provider, null, React.createElement(Component, pageProps)));
>      |  ^
>   17 | }
>   18 | 
>   19 | export default MyApp;
> ```

Happened with me too when I tried using useState in _app.js
A little workaround that worked for me was that, instead of 
```
import { useState } from 'react'
```
I used
```
import React from 'react'

const [...] = React.useState(...)
```

**Comment by ydrea** [comment]
Tnx Xinha!

**Comment by xinha-sh** [comment]
@ydrea You should keep this open as the above solution is a hacky solution.

Maybe this is an issue, for swc minification to work next should be min 12.3

https://stackoverflow.com/questions/73913651/nextjs-swc-react18-referenceerror-react-is-not-defined

**Comment by nandorojo** [comment]
yeah this is odd. if you disable SWC minify and use babel instead, does it get fixed? you may need to clear out `node_modules` and `.next` folders, run `yarn` and then `yarn web` again.

**Comment by ydrea** [comment]
I am not using SWC...

**Comment by nandorojo** [comment]
what if you run `yarn why react`?

my guess is there are multiple versions installed

**Comment by nandorojo** [comment]
I couldn't reproduce this with the monorepo starter.

**Comment by nandorojo** [comment]
Ah, never mind, I see. If you don't `import React` inside of `_app.tsx`, it does indeed throw this error. I'm not exactly sure why. For now, just stick to the workaround. Next 13 is right around the corner, and we won't even have this file anymore.
