### ISSUE TITLE
Using pure react-native component instead of dripsy

### ISSUE THREAD

**Issue by agallio** [nandorojo/solito#18]
Is there any way or any idea how to use pure react-native/react-native-web component instead of dripsy?

**Comment by nandorojo** [comment]
of course! just swap them in wherever you see dripsy components. it’s a very bare example, so it’s only in a few files

**Comment by agallio** [comment]
Unfortunately, TS doesn't recognize it because of the `rnw-overrides` I guess.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/22767465/158362768-85bf1c5b-39d9-4f6e-a3ef-830eed12b050.png">

Is there any workaround? Or do I simply just `yarn add react-native` to the `packages/app` directory?

**Comment by nandorojo** [comment]
hmm that’s weird. No react native shouldn’t be there.

we might need to add `@types/react-native` in `app` (or in the root of the monorepo) in `devDependencies`

if it’s in the root, try `yarn add @types/react-native -W`

**Comment by agallio** [comment]
`@types/react-native` is already inside the [create-solito-app's `package.json`](https://github.com/nandorojo/solito/blob/bc9a4f7f5dac3913317824324bf384a7a59217cd/example-monorepos/blank/package.json#L10).

I tried to add it to the `packages/app` directory as a devDependencies, but no luck. The error is still there 🤔

**Comment by nandorojo** [comment]
hmm lemme see

**Comment by nandorojo** [comment]
ah this is my fault. it's from the declaration merging file

**Comment by nandorojo** [comment]
Fixed in the monorepo: https://github.com/nandorojo/solito/commit/b6206c5d9710d72971a4fb1689334ad0a1a59802

Closing now, thank you for the find!
