### ISSUE TITLE
Image Error: TypeError: unsupported file type: undefined

### ISSUE THREAD

**Issue by rizaldirnm** [nandorojo/solito#182]
I use `<Image />` from `dripsy` and attempt to show image with `.png` extention.

Try to run in Web (nextjs) with `yarn web` but the error appear

The code look like:
```
      <H1 sx={{ fontWeight: '800' }}>Welcome to Solito.</H1>
      <Image source={require("./test-image.png")} /> // --> I added code here Image from Dripsy
```

On IOS works but on the web show me the error like:

```
../../packages/app/features/home/test-image.png
TypeError: unsupported file type: undefined (file: undefined)
```

Iam using Blank Template also I havent edit anything in config nextjs.

**Comment by rizaldirnm** [comment]
Just try it `images.disableStaticImages: true` , and still have same issue

> does your next config file have next-image installed?
yes.

My current `next.config.js`

```
const { withExpo } = require('@expo/next-adapter')
const withFonts = require('next-fonts')
const withImages = require('next-images')
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')([
  'solito',
  'dripsy',
  '@dripsy/core',
  'moti',
  'app',
])

/** @type {import('next').NextConfig} */
const nextConfig = {
  // reanimated (and thus, Moti) doesn't work with strict mode currently...
  // https://github.com/nandorojo/moti/issues/224
  // https://github.com/necolas/react-native-web/pull/2330
  // https://github.com/nandorojo/moti/issues/224
  // once that gets fixed, set this back to true
  reactStrictMode: false,
  webpack5: true,
  images: {
    disableStaticImages: true
  }
}

const transform = withPlugins([
  withTM,
  withFonts,
  withImages,
  withExpo,
])

module.exports = function (name, { defaultConfig }) {
  return transform(name, {
    ...defaultConfig,
    ...nextConfig,
  })
}

```

**Comment by jysung** [comment]
I am struggling with the same issue for the last week. 
This happens both with or without `dripsy`.

**Comment by Puneet56** [comment]
remove .babelrc.json from nextjs project and images will work. But the inline className will not work, you have to wrap the components into styled() and export or use them.

**Comment by jysung** [comment]
@Puneet56 That does not work for me.

@nandorojo It is very reproducible with any new starter project I create with Solito. It makes the whole solito starter project not usable. I would really appreciate it if you can at least let me know if it is reproducible on your end or not.

**Comment by nandorojo** [comment]
Hey, please keep in mind that this is all my time and work given out for free. There's no need to ping me to see if I can fix it. If you can try to engineer a solution, that would be great. Otherwise, I will take a look when I have free time.

**Comment by nandorojo** [comment]
Please find a summary of the fixes here: https://github.com/nandorojo/solito/commit/71226dc83d5c36a1eb15f48c0473024d0688f01e

If you want to use SWC, you can uncomment the `experimental` field in Next Config.

Thanks!

**Comment by rizaldirnm** [comment]
I found the problem here.

you can drop `next-compose-plugins` and compose by yourself.

This is my latest `next.config.js` and run smoothly.

```
const { withNx } = require('@nrwl/next/plugins/with-nx');
const { withExpo } = require('@expo/next-adapter');
const withFonts = require('next-fonts');
const withImages = require('next-images');
const withTM = require('next-transpile-modules')([
  'solito',
  'dripsy',
  '@dripsy/core',
]);

module.exports = async () => {
  /**
   * @type {import('@nrwl/next/plugins/with-nx').WithNxOptions}
   **/
  const nextConfig = {
    nx: {
      // Set this to true if you would like to to use SVGR
      // See: https://github.com/gregberge/svgr
      svgr: false,
    },
    reactStrictMode: false,
    images: {
      disableStaticImages: true,
    },
  };

  const plugins = [withNx, withTM, withImages, withFonts, withExpo];

  return plugins.reduce((acc, plugin) => plugin(acc), { ...nextConfig });
};
```
