### ISSUE TITLE
Weird error while using with Supabase

### ISSUE THREAD

**Issue by galacoder** [nandorojo/solito#187]
Hi, 

I am trying to use Solito app with Supabase, but I keep hitting this weird error. Please advise!

Your earliest help is very much appreciated.

[with-tailwind.zip](https://github.com/nandorojo/solito/files/9816461/with-tailwind.zip)

![z3811226346070_230b702ac2cb08a4d87bf42c7dc8006f](https://user-images.githubusercontent.com/13715145/196587213-e11be5b0-9bd2-4134-9a55-2acea4e78786.jpg)

<img width="1002" alt="Screen Shot 2022-10-19 at 09 48 41" src="https://user-images.githubusercontent.com/13715145/196587229-6f432b9d-07f0-43a9-b0d8-bf9cea912c48.png">

**Comment by nandorojo** [comment]
this doesn’t seem related to solito. also, it’s better to share a github repo than a zip file fyi.

**Comment by galacoder** [comment]
Hi @nandorojo, 

Thanks for your timely response.

Sorry. Here is my project link: https://github.com/galacoder/project-you

Please advise!
