### ISSUE TITLE
useRouter replace on ios/andriod

### ISSUE THREAD

**Issue by jeffreybrowning** [nandorojo/solito#201]
Great library. I'm attempting to hide the back button in the react-navigation header on a screen after rerouting from an onboarding flow. It does seem possible that you can use path in nested navigate payloads.

From here https://reactnavigation.org/docs/configuring-links/ the resulting action includes path: 
```
{
  "type": "NAVIGATE",
  "payload": { 
    "name": "Home",
    "params": {
      "initial": false,
      "screen": "Profile",
      "params": {
        "id": "vergil",
        "initial": true,
        "screen": "Settings",
        "path": "/user/@vergil/edit"
      }
    }
  }
}
```

**Comment by nandorojo** [comment]
> Great library. 

thanks!

as for the rest of your comment, I don’t understand how to help.

**Comment by nandorojo** [comment]
Hey @jeffreybrowning, I released a new version that adds stack replace functionality to the `replace()` function (and `<Link />` component).

Could you see[ these docs](https://github.com/nandorojo/solito/releases/tag/v1.1.2) and try it out on the latest version of Solito (`1.1.2`?) Thanks!

**Comment by jeffreybrowning** [comment]
Legend. Thanks so much for your time. Will do so today.
