### ISSUE TITLE
[Done] Next.js 13 support

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/solito#202]
👀

```sh
yarn add solito
```

Update: available in v2: https://solito.dev/v2

**Comment by chrisarts** [comment]
Im creating a design system for dripsy but cant find a way to create a patch due the next transpile modules library needs to support next13 to create that, do we have another option?

**Comment by corysimmons** [comment]
Looks like Next 13 has module transpiling built-in: https://github.com/martpie/next-transpile-modules/issues/280#issuecomment-1292615030

**Comment by seanaguinaga** [comment]
🙏

**Comment by nandorojo** [comment]
PR opened at #216

**Comment by corysimmons** [comment]
@martpie & @nandorojo supporting the bleeding edge in a few days! 👏 ❤️

**Comment by nandorojo** [comment]
I think this is good to go...

```sh
yarn add solito@next13
```

**Comment by nandorojo** [comment]
Hey all, upgrade guide is here: https://solito.dev/v2

Leaving this open for visibility.
