### ISSUE TITLE
Solito Link doesn't work with new Expo Router

### ISSUE THREAD

**Issue by galacoder** [nandorojo/solito#203]
Hi Fernando,

As you suggested, I am trying out Expo Router with Solito. However, it seems like Solito Link/TextLink is not supported latest Expo Router yet. I got the error (see attachment). It worked when I tried to use Expo Router Link component tho.

In addition, it also worked when I tried to use your example with `npx create-solito-app@latest -t with-expo-router`

Here is my repo: https://github.com/galacoder/project-you/tree/switch-to-expo-router

Please advise!
Your earliest help is appreciated.
Tks! 

![IMG_6720](https://user-images.githubusercontent.com/13715145/197932608-c1e3e622-6b7f-447e-a6d6-8ee8c292f688.jpg)

**Comment by nandorojo** [comment]
I think you need to remove any react navigation packages from your package.json, since it's causing multiple versions to get installed

**Comment by nandorojo** [comment]
you should also remove `@motify` packages

**Comment by galacoder** [comment]
Thank you for your timely response. It's working beautifully. 

Now I can save so much time and having so much fun using the power of Solito + Expo Router.  

Cheers :)

**Comment by nandorojo** [comment]
cool!
