### ISSUE TITLE
First render page stylization

### ISSUE THREAD

**Issue by gabrielEloy** [nandorojo/solito#210]
Hello, Fernando! I hope you are doing fine!

I'm having a problem with my nextJS application taking a while to load on the user's first access and during that time, the user sees a blank screen

take a look at this lighthouse report output.

<img width="814" alt="image" src="https://user-images.githubusercontent.com/37480915/198625798-6b5f6d62-5ec0-4c5d-94f8-962252edf773.png">

Do you see how the first 8 screenshots show a white page ?

When running the same audit on Beatgig, the initial blank page is black instead of white. how were you able to do it ? 

<img width="817" alt="image" src="https://user-images.githubusercontent.com/37480915/198631853-d0a95549-e43b-4fc7-b69b-d4fec57f99eb.png">

I would like to do the same while I work on a more permanent solution for my app

**Comment by nandorojo** [comment]
weird that your initial load took that much longer. As for black — I set the body background in a `style` tag in `_app.tsx` outside of any providers

**Comment by gabrielEloy** [comment]
Yeah. I'm still investigating why my initial load is taking so much time. Thank you so much for your answer! It was very helpful!

I hope you have a good weekend!
