### ISSUE TITLE
⚡️ Instantly clone & deploy is not happy

### ISSUE THREAD

**Issue by flexbox** [nandorojo/solito#22]
As a developer
I can clone and deploy on vercel
So that I can try if it's working

![image](https://user-images.githubusercontent.com/360936/158577953-46173e43-7be3-474a-b530-dd66bcc6ea36.png)

When we hit the deploy button...

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2Fnandorojo%2Fsolito%2Ftree%2Fmaster%2Fexample-monorepos%2Fblank&env=ENABLE_ROOT_PATH_BUILD_CACHE&root-directory=/apps/next&envDescription=Set%20this%20environment%20variable%20to%201%20for%20Turborepo%20to%20cache%20your%20node_modules.&envLink=https%3A%2F%2Ftwitter.com%2Fjaredpalmer%2Fstatus%2F1488954563533189124&project-name=solito-app&repo-name=solito-app&demo-title=Solito%20App%20%E2%9A%A1%EF%B8%8F&demo-description=React%20Native%20%2B%20Next.js%20starter%20with%20Solito.%20Made%20by%20Fernando%20Rojo.&demo-url=https%3A%2F%2Fsolito.dev%2Fstarter&demo-image=https%3A%2F%2Fsolito.dev%2Fimg%2Fog.png)

...it's impossible to

> - Select the folder apps/next as the root of your Next.js app on the Vercel setup.

I have a feeling we can add some params to fix it, but I don't know which one 😅

https://github.com/nandorojo/solito/blob/e2f41ee89f2dc46dbdaa2d9fe74e9678dec66da6/example-monorepos/blank/readme.md?plain=1#L11

**Comment by nandorojo** [comment]
ah! this must be due to #15. the param is `root-directory`, which should point to `apps/next`

**Comment by nandorojo** [comment]
The button you linked to worked fine for me. I assume the broken one is at solito.dev/starter?

**Comment by flexbox** [comment]
I tried from https://github.com/nandorojo/solito/tree/master/example-monorepos/blank

**Comment by nandorojo** [comment]
I see, you’re right. Is root-directory defined there? I’m on my phone so it’s hard for me to check

**Comment by nandorojo** [comment]
fixed from my phone lol: https://github.com/nandorojo/solito/commit/eed3f3e9bf58138eb5072cee1eaa98355c9f5204

**Comment by flexbox** [comment]
🤔 

thanks for the input, I tried with 
![image](https://user-images.githubusercontent.com/360936/158580207-2ac71d8b-c488-4c5e-b472-30eb9ff82223.png)
```
&root-directory=apps/next
```
and not
```
&root-directory=/apps/next
```

![image](https://user-images.githubusercontent.com/360936/158580126-56649d0f-dfae-44de-87cb-e3efe11b3830.png)

Vercel seam happy

**Comment by nandorojo** [comment]
thanks for the heads up! any chance you’d copy this the updated button to the solito “starter” page in the docs through a PR?

**Comment by flexbox** [comment]
@nandorojo 😂
you are a legend

I will have a look!

**Comment by flexbox** [comment]
> thanks for the heads up! any chance you’d copy this the updated button to the solito “starter” page in the docs through a PR?

It was the good param, I tried from [solito.dev/starter](https://solito.dev/starter)

![image](https://user-images.githubusercontent.com/360936/158580784-8b45a5e0-6d37-42b7-9215-6b77c8289028.png)

All good now!
