### ISSUE TITLE
does not seem to compile android when I try `    "android": "cd apps/expo && expo android"` script

### ISSUE THREAD

**Issue by hitesh97** [nandorojo/solito#221]
Hi there, I am trying to use this template for my monorepo.

followed the instruction on readme and it works on `Expo client` when I run the script `web or native` however, when I added a new script target on the root package.json

`    "android": "cd apps/expo && expo android"`

and then if I run `yarn android` it doesnt compile.

it throws following error

`
> Task :react-native-gradle-plugin:compileKotlin FAILED
'compileJava' task (current target is 1.8) and 'compileKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-gradle-plugin:compileKotlin'.
> Failed to query the value of task ':react-native-gradle-plugin:compileKotlin' property 'compilerRunner$kotlin_gradle_plugin'.
   > Kotlin could not find the required JDK tools in the Java installation. Make sure Kotlin compilation is running on a JDK, not JRE.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
1 actionable task: 1 executed
Error: /Users/hiteshkhatri/Documents/personal/projects/my-solito-app-2/apps/expo/android/gradlew exited with non-zero code: 1
Error: /Users/hiteshkhatri/Documents/personal/projects/my-solito-app-2/apps/expo/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/hiteshkhatri/Documents/personal/projects/my-solito-app-2/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

any ideas, what I am doing wrong?

I can compile the vanilla `EXPO project` created with expo cli with `android script` without any issues.
just to verify that i have all the required Java and JDK /JRE is installed etc.

**Comment by nandorojo** [comment]
you need to use `expo run:android` to generate a dev client if you’re using native libraries. then you can start a dev server with `expo start —dev-client`
