### ISSUE TITLE
Solito does not work on windows

### ISSUE THREAD

**Issue by gabrielesilinic** [nandorojo/solito#229]
i don't ask you to make it work, i mean, it would be nice but it's not mandatory, just add it to the docs because i spent a week of my life figuring out why it wouldn't run

the issue appears as missing dependencies and errors building packages, i used WSL2 to make the web build work, now i have to figure out port forwarding to my windows browser

**Comment by nandorojo** [comment]
I'm not exactly sure I understand why it doesn't work. Do you mean that `create-solito-app` doesn't work? I don't see why `solito` itself wouldn't work, since it's just an NPM package.
