### ISSUE TITLE
Typescript errors on string Dripsy components

### ISSUE THREAD

**Issue by thomas-claireau** [nandorojo/solito#23]
Hi,

First, thank you for your work

I am currently testing Solito and I have a Typescript error (ts2322 - capture below) on all Dripsy components of type string

<img width="956" alt="CleanShot 2022-03-16 at 12 27 36@2x" src="https://user-images.githubusercontent.com/45904840/158580865-45a376f8-831a-44d0-9f5b-beecbe710a06.png">

I saw this issue https://github.com/nandorojo/dripsy/issues/67 on your Dripsy repo but it didn't work for me

Would you have any idea?
Thx

**Comment by nandorojo** [comment]
I think I need more info here besides just that screenshot. I’m not sure what the issue is. Can you put all the code

**Comment by nandorojo** [comment]
Is this in the solito starter? If not can you open this on the Dripsy repo

**Comment by thomas-claireau** [comment]
Yes its the solito starter but I added some code in the app. The package and yarn.lock file has been modified to add some libraries (https://github.com/thomas-claireau/solito-test/commit/c4147d1aa57e430e8f5cf256f8225076e645e806) that are useful to me but nothing more

The file concerned by the error above : https://github.com/thomas-claireau/solito-test/blob/main/packages/app/features/home/screen.tsx

**Comment by nandorojo** [comment]
hm, did you run `yarn` in the root of the repo?

**Comment by thomas-claireau** [comment]
yes and the deps include in yarn.lock are exactly the same as solito starter (except packages libraries added)

**Comment by nandorojo** [comment]
I’m not sure, maybe restart VSCode? is it just H1? is it the sx prop?

**Comment by nandorojo** [comment]
Hmm so this happens on a fresh clone? Let me try it myself.

**Comment by thomas-claireau** [comment]
Hi, nop, on a fresh clone, I don't have any error. 
But, on my repo, I don't understand where the errors come from

**Comment by thomas-claireau** [comment]
It's like the types from @expo/html-elements don't recognized

**Comment by nandorojo** [comment]
Oh, I see. 

Can you try this? https://github.com/nandorojo/solito/commit/b6206c5d9710d72971a4fb1689334ad0a1a59802

**Comment by nandorojo** [comment]
Make sure `import 'react-native'` is at the top of `packages/app/rnw-overrides.ts`

**Comment by thomas-claireau** [comment]
Ah yes that was it ! Thanks a lot 🙏

**Comment by josmithua** [comment]
Hey there, I'm converting an expo app over to solito, and I'm having this same issue, even with the import in `rnw-overrides.ts`. Any suggestions?

**Comment by nandorojo** [comment]
it may depend on where you’re installing certain packages, as well as where your tsconfig files are, and where the override file is. I recommend looking at the solito starter to copy these things

**Comment by nandorojo** [comment]
what if you use the solito starter app, does it happen there?

**Comment by josmithua** [comment]
It does not. So something's off, just gotta find it :/

**Comment by nandorojo** [comment]
restart VS Code? `yarn why typescript`?

**Comment by josmithua** [comment]
Restarted multiple times, and yarn why typescript returns the same for my app as the starter app (barring name and guid differences)

**Comment by nandorojo** [comment]
maybe try copying your code / packages into a solito starter

**Comment by nandorojo** [comment]
did you do the dripsy makeTheme with declaration merging? shouldn’t be needed but just an idea

**Comment by josmithua** [comment]
I think I will slowly copy components over to the starter and then 

> maybe try copying your code / packages into a solito starter

That is what I am doing now, slowly copying everything over to the starter. Hopefully I'll discover what's making the types not work.

**Comment by josmithua** [comment]
Hi @nandorojo,

After a lot of working, I discovered that this issue comes up if you do a `yarn upgrade` in the solito starter. So reproducible steps:

1. `npx create-solito-app@latest blank-solito-app`
2. `cd blank-solito-app`
3. `yarn upgrade`
4. `yarn tsc`

Step 4 will produce (as of this writing):

```
...

Found 14 errors in 4 files.

Errors  Files
     1  apps/next/pages/_app.tsx:19
    10  packages/app/features/home/screen.tsx:9
     2  packages/app/features/user/detail-screen.tsx:11
     1  packages/app/navigation/native/index.tsx:15
error Command failed with exit code 2.
```

**Comment by nandorojo** [comment]
why are you doing yarn upgrade?

**Comment by josmithua** [comment]
In my case I didn't run `yarn upgrade`: When copying files from the starter to my own project, I just ran `yarn` to install the new packages from the updated/new `package.json` files (I didn't copy over the `yarn.lock` file because I already had one).

**Comment by nandorojo** [comment]
presumably there’s some other package causing the issue

**Comment by nandorojo** [comment]
> Question:
> 
> The readme says:
> 
> > If you're installing a library with any native code, you must install it in apps/expo: ...
> > You can also install the native library inside of packages/app if you want to get autoimport for that package inside of the app folder.
> 
> The starter uses `@react-navigation/native` and `@react-navigation/native-stack`, but they are only installed in packages/app, not apps/expo. This seems to contradict the readme?

these are both JS-only libraries
