### ISSUE TITLE
How can I get navigation prop by solito?

### ISSUE THREAD

**Issue by arshelia** [nandorojo/solito#231]
I had an old native app which use react-navigation4.x,  and had tried migrated it to build web application by solito as well. The first difficulty blocked me is how can I get navigation prop with solito, for the 4.x, I can  use api as belows:
`import { useNavigation } from 'react-navigation-hooks`
But is solito, navigation is not export at `useRouter`, and I wondered is there any solution or plane to enhance navigation functionality?

**Comment by nandorojo** [comment]
what features of navigation do you need? have you read the docs for screen parameters and tree shaking?

**Comment by arshelia** [comment]
> what features of navigation do you need? have you read the docs for screen parameters and tree shaking?

For example, `StackActions.reset` and `navigation.addListener`. But as you metioned above, maybe I can try to create platform-specific module including the features that I need.

**Comment by nandorojo** [comment]
In these cases, I would create platform-specific modules. But also make sure you need them first!

**Comment by nandorojo** [comment]
Also, if it helps, I just released a feature to use `StackActions.replace` with Solito: https://github.com/nandorojo/solito/releases/tag/v1.1.2
