### ISSUE TITLE
Does not give eslint errors in Webstorm IDE or VSCode

### ISSUE THREAD

**Issue by RobinLindhout** [nandorojo/solito#24]
We started a new Solito project but we can't get eslint to work in the IDE.

![Schermafbeelding 2022-03-17 om 10 12 59](https://user-images.githubusercontent.com/79744544/158776497-cd211330-82ad-4fa8-a532-b05ab5a4001d.png)
![Schermafbeelding 2022-03-17 om 10 13 04](https://user-images.githubusercontent.com/79744544/158776501-5a89f299-1ec6-4d23-8f12-a2892a21e95f.png)
![Schermafbeelding 2022-03-17 om 10 13 12](https://user-images.githubusercontent.com/79744544/158776507-e453d588-bbeb-4264-a480-3c7397354d23.png)

**Comment by RobinLindhout** [comment]
When we add 
```
yarn add @next/eslint-plugin-next --dev -W
```
we got
![Schermafbeelding 2022-03-17 om 10 20 17](https://user-images.githubusercontent.com/79744544/158777768-0ff425c4-5c26-4c36-92cb-9dc66df24ca4.png)

**Comment by RobinLindhout** [comment]
When we use
```
module.exports = {
  extends: 'next/core-web-vitals',
}

```
as base + yarn add next eslint eslint-config-next --dev -W in the root package it starts working.


But no errors in IDE on not existing properties
![Schermafbeelding 2022-03-17 om 10 27 40](https://user-images.githubusercontent.com/79744544/158779146-9a567895-5348-4a3e-b9f3-b64d0aeb76df.png)

**Comment by nandorojo** [comment]
I was getting issues with ESLint too…I wonder if that eslint file should be installed in the Next folder? As you’ll see in the starter, I some ESLint config issues from the new Next.js linter.

**Comment by nandorojo** [comment]
the image you sent shouldn’t break, since background color accepts any string. Is that what you’re referring to?



> When we use
> 
> ```
> module.exports = {
>   extends: 'next/core-web-vitals',
> }
> ```
> 
> as base + yarn add next eslint eslint-config-next --dev -W in the root package it starts working.
> 
> But no errors in IDE on not existing properties ![Schermafbeelding 2022-03-17 om 10 27 40](https://user-images.githubusercontent.com/79744544/158779146-9a567895-5348-4a3e-b9f3-b64d0aeb76df.png)

**Comment by RichardLindhout** [comment]
But in your demo video it give errors when e.g. wrong spacing was being used

**Comment by RichardLindhout** [comment]
It does give errors in the terminal though just not in the IDE.

**Comment by nandorojo** [comment]
> It does give errors in the terminal though just not in the IDE.

I had this same issue. I got around it by silently breaking the `next lint` command with an incorrect ESLint config. Looking into this now for a fix

**Comment by RichardLindhout** [comment]
I don't know if eslint can understand it if we use eslintrc for expo and in nextjs folder we can use nextjs linting too

**Comment by RichardLindhout** [comment]
Should be nice if we could use nextjs things only in next project and react native + web linting in packages/app

**Comment by nandorojo** [comment]
Yeah, that's more of a monorepo question in general. It feels like it should be possible if we `extend` the ones we want in each folder. That said, I'm a bit confused why this error comes up, only when I install next's ESLint plugin and run `yarn build`:

```sh

yarn run v1.22.5
$ next build
info  - Checking validity of types  

Failed to compile.

./pages/_app.tsx
1:1  Error: Parsing error: The keyword 'import' is reserved

./pages/_document.tsx
1:1  Error: Parsing error: The keyword 'export' is reserved

./pages/index.tsx
1:1  Error: Parsing error: The keyword 'import' is reserved

./pages/user/[id].tsx
1:1  Error: Parsing error: The keyword 'import' is reserved

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
error Command failed with exit code 1.
```

**Comment by nandorojo** [comment]
Made some progress with this in the `apps/next/.eslintrc.js` file:

```js
module.exports = {
  extends: 'next',
}
```

I also installed `@next/eslint-plugin-next` in `apps/next`. Still some errors but it builds.

**Comment by nandorojo** [comment]
See this commit (ignoring the `yarn.lock` changes to see how I fixed it in the example): https://github.com/nandorojo/solito/commit/d9e40a4545c47a5aefae5b3a12ba55e738f71b1b

You can also run `npx create-solito-app@latest` if you want, but since you already have an app started, you'll probably want to copy over those changes.

Thanks for opening the issue, hope that fixes it on your end! Please let me know if it does.

**Comment by RichardLindhout** [comment]
Amazing we will try it out soon!

**Comment by RichardLindhout** [comment]
Moti is amazing btw <3. First time I used it and it's so easy to write cool animations.
