### ISSUE TITLE
Sticky Component is not working

### ISSUE THREAD

**Issue by bipin-goodworklabs** [nandorojo/solito#244]
Hii,
I have a ad page which has sticky form.
in react native base it is working fine but when i am integrating the nextjs (solito) then it is not working.
i searched alot but nothing found.

![image](https://user-images.githubusercontent.com/92708856/203097961-a8ad74c7-c19f-4b96-8651-6154af3c4129.png)

following is my code for ad sticky  form which was working.

` <ScrollView stickyHeaderIndices={[0]} ref={scrollViewRef}>
        <Hidden till="md">
          <View>
            <AdForm
              name={name}
              email={email}
              phone={phone}
              error={error}
            />
          </View>
        </Hidden>
        </ScrollView>`
        
        the above code was working fine just with react native base but with nextjs solito not working
Please help me
thanks

**Comment by nandorojo** [comment]
Did you read the docs for scroll views? https://solito.dev/recipes/scroll-view

You likely need to wrap your `ScrollView` like this:

```tsx
<View style={{ flex: 1 }}>
  <ScrollView />
</View>

**Comment by bipin-goodworklabs** [comment]
No that is not working.

**Comment by bipin-goodworklabs** [comment]
I moved the sticky form out of scrollview and added it in view and that worked
<View
          position="sticky"
          top={'2'}
          right="30"
          width={'100%'}
          zIndex={9999999999999}
        ><AdForm></View>
