### ISSUE TITLE
solito website side nav on mobile looks broken

### ISSUE THREAD

**Issue by doubleppereira** [nandorojo/solito#248]
Steps:
1. Opened [https://solito.dev/](https://solito.dev/) on mobile viewport
2. Clicked on the side nav button to open:
<img width="497" alt="Screenshot 2022-11-26 at 13 25 34" src="https://user-images.githubusercontent.com/1664583/204091210-fbc74d40-9fa9-46b4-8f60-f453fa6d5fd2.png">

3. Displays as follows:
<img width="462" alt="Screenshot 2022-11-26 at 13 26 05" src="https://user-images.githubusercontent.com/1664583/204091234-1485220d-ca0e-4f4a-8f92-0d61e758fd97.png">

It happens on Chrome, Safari and Firefox

**Comment by nandorojo** [comment]
weird! works for me…

![720A7C33-0654-480C-B8BA-85E070FA0B4C](https://user-images.githubusercontent.com/13172299/204091612-9a6b2013-a51a-4837-95b7-6e5a7f8bb35b.png)

**Comment by doubleppereira** [comment]
Tested in my Mac with all 3 browsers and my Android device. Same result

**Comment by doubleppereira** [comment]
Androidn screenshot:
![Screenshot_2022-11-26-13-42-10-33](https://user-images.githubusercontent.com/1664583/204091899-4a5fd625-553f-470f-b833-36b4ba456991.jpg)

**Comment by nandorojo** [comment]
thanks for testing all that. i wonder what’s causing it

**Comment by doubleppereira** [comment]
could it be cache? Getting this on the response headers:
<img width="278" alt="Screenshot 2022-11-26 at 14 10 39" src="https://user-images.githubusercontent.com/1664583/204093028-bb7d1431-4bf6-4f39-b7dd-d6d1c0fb6871.png">
 it could explain why it looks ok for you and not from my side.. region cache.. just throwing ideas 😅

**Comment by nandorojo** [comment]
yeah that could be it

**Comment by doubleppereira** [comment]
I can't give any other culprit since this was built in docusaurus. 🤷🏼‍♂️ someone could have seen this bug before I guess.

**Comment by navanshu** [comment]
This might help use 100vh instead of 100%;

```css
.navbar-sidebar {
 overflow: visible
}

.navbar-sidebar__items {
 height: calc(100vh - var(--ifm-navbar-height))
}
```
