### ISSUE TITLE
Mixed nextjs web + react native

### ISSUE THREAD

**Issue by rodbs** [nandorojo/solito#25]
I have a Nextjs website, which has a part that I'd like to keep just web (http://xxx.com/blog )  , and other part that I'd like to share with React Native  (http://xxx.com/app) .
Is it possible? How can I do it while keeping everything in the same repo? I mean, I don't want the blog side to appear in the app for react native.

Thanks

**Comment by nandorojo** [comment]
The app and website never speak to each other, so achieving this is simple. You do exactly what you think you'd do: only import pages on Next.js that you want on Next.js. If you don't want them on the app, don't import them inside of `apps/expo`. And that's all!

**Comment by nandorojo** [comment]
To clarify, any monorepo code that isn't imported in the next site/mobile app will never show up there. You have to import it somehow for it to be shown to a user.

**Comment by rodbs** [comment]
Ok, I think I understand what you mean!
Thanks!
