### ISSUE TITLE
add a proper replace function in useRouter hook for redirects

### ISSUE THREAD

**Issue by aleedmanath** [nandorojo/solito#252]
I'm using Solito with expo-router. I need a way to `replace` a route for redirects, so that previous one is not in navigation stack and  the user can not navigate back to it. 

Solito's `useRouter().replace` was not exhibiting this behavior. The docs do explain this limitation:

> On iOS and Android, this function doesn't call actually replace(). Instead, it calls [linkTo from React Navigaton](https://reactnavigation.org/docs/use-link-to/).
>
>This is because React Navigation doesn't currently offer an API to replace a current route with a URL.
>
>If this is a big need for you, please open an issue.

Opening this issue to discuss proper way forward, as I know Solito's primary target is `react-navigation` not `expo-router` 

I'm currently doing `useLink().replace` as an alternative.

Perhaps Solito could have a different file export `solito/expo-router` that handles this properly.

**Comment by nandorojo** [comment]
Solito now includes this behind an experimental flag.

https://github.com/nandorojo/solito/releases/tag/v1.1.2

**Comment by aleedmanath** [comment]
nice, i'll close issue
