### ISSUE TITLE
pnpm

### ISSUE THREAD

**Issue by steida** [nandorojo/solito#255]
Hi, just curious whether there is a reason to use Yarn. Many people (including me) switched to pnpm because it's faster and more reliable (especially in mono repo). Yarn with its versions is confusing. I am asking because Solito proposes best practices. Thank you for your work.

**Comment by nandorojo** [comment]
Yeah pnpm seems great! As long as it works for you should go for it. I’ve tried migrating but had too many difficulties in my existing app.
