### ISSUE TITLE
Solito Image in Expo Go

### ISSUE THREAD

**Issue by marytal** [nandorojo/solito#256]
Hi! 
I'm seeing the following error: `Unable to resolve "../build/image/expo" from "../../node_modules/solito/image/expo/index.js"` when loading up my Expo Go app. 

I'm using the [`next13` branch](https://github.com/nandorojo/solito/tree/next13) as my solito version because I wanted to try out `solito/image`. I adjusted my babel config to alias `solito/image` to `solito/image/expo`:
```JavaScript
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [['babel-preset-expo', { jsxRuntime: 'automatic' }]],
    plugins: [
      'nativewind/babel',
      'react-native-reanimated/plugin',
      [
        'module-resolver',
        {
          root: ['./'],
          alias: {
            'solito/image': 'solito/image/expo',
          },
        },
      ],
    ],
  }
}

```

Things are working fine in my web app. 
Do you have any ideas why Expo Go might be unable to resolve `../../build/image/expo` even though I can see that it's a valid route? 

I'm fairly new to JavaScript / yarn / npm etc.

**Comment by nandorojo** [comment]
can you install the latest version? `yarn add solito`

**Comment by nandorojo** [comment]
Oh I think I see a problem. One sec.

**Comment by nandorojo** [comment]
Just fixed it, should be in version `2.0.8`. You can change this version in your `package.json` and run `yarn` at the root.

**Comment by nandorojo** [comment]
Let me know if that fixes it!

**Comment by marytal** [comment]
Thanks! Trying now :)

**Comment by marytal** [comment]
The error is gone! Thanks 🙇 🙇 🙇

**Comment by nandorojo** [comment]
cool
