### ISSUE TITLE
`replace()` should support deeply-nested navigators

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/solito#261]
If you have tabs → stack → modal → another stack, the new `isNestedNavigator` field is insufficient since it only checks one layer deep for nested navigators. 

There should be an alternative `nestedNavigatorCount` (or something like it) so that we know how deep the nested navigators need to go. Alternatively, there could be a behavior that is told to go as deep as possible vs a set number of layers:

```js
replace('/', undefined, { nativeBehavior: 'stack-replace', nestedNavigatorBehavior: 'recursive' | 2 })
```

Setting `recursive` would tell Solito to go all the way to the root stack. Alternatively, you could tell it how many layers deep it should go with a number.

**Comment by vinodsptharsha** [comment]
Is this being considered for future release? I think it is a must have feature for majority of the apps involving complex routing systems.

**Comment by nandorojo** [comment]
Yes it is

**Comment by nandorojo** [comment]
will reopen this if i have time in the future to implement it.
