### ISSUE TITLE
How to implement responsive SolitoImage using nativewind ?

### ISSUE THREAD

**Issue by xinha-sh** [nandorojo/solito#269]
Hi I'm using nativewind for styling. And my image component looks like this

```tsx
import { styled } from 'nativewind'
import { SolitoImage } from 'solito/image'

export const Img = styled(SolitoImage)
```

```tsx
<Img
  className="h-16 w-16 self-center rounded-full border-2 border-slate-600 hover:border-4 hover:border-yellow-600 md:h-32 md:w-32"
  src={vertical.imageUrl}
  resizeMode="contain"
  alt={vertical.name}
 />
```
Error shown is

<img width="1051" alt="Screenshot 2022-12-06 at 5 44 03 PM" src="https://user-images.githubusercontent.com/107257599/205909825-ee02a6c2-1327-4a0b-ba5c-072ac71498ae.png">

I'm able to bypass this error via adding a style prop with ``{{}}`` as value. ie
```tsx
<Img
  className="h-16 w-16 self-center rounded-full border-2 border-slate-600 hover:border-4 hover:border-yellow-600 md:h-32 md:w-32"
  src={vertical.imageUrl}
  resizeMode="contain"
  alt={vertical.name}
  style={{}}
 />
```

But after that I'm getting following error:

<img width="1051" alt="Screenshot 2022-12-06 at 5 46 10 PM" src="https://user-images.githubusercontent.com/107257599/205910297-1ae57f33-4ffd-4fc6-b1d8-3357b924d82b.png">

**Comment by nandorojo** [comment]
I’ll look into the style issue. Width is required unless you use the `fill` property.

**Comment by nandorojo** [comment]
I actually don’t think this is a solito image issue. If you use it directly, the style prop isn’t required. So it must be an issue with nativewind’s styled()

**Comment by xinha-sh** [comment]
> I actually don’t think this is a solito image issue. If you use it directly, the style prop isn’t required. So it must be an issue with nativewind’s styled()

Got it.Thanks

**Comment by xinha-sh** [comment]
@nandorojo I stumbled upon this youtube video regarding next/image. It's in-dept and I felt should be included in solito docs. Hence raising a PR https://github.com/nandorojo/solito/pull/271

**Comment by nandorojo** [comment]
You should wrap `solito/image` with `styled` by the way.
