### ISSUE TITLE
"⚡️ Instant Clone & Deploy" TailwindCSS Example not working

### ISSUE THREAD

**Issue by chen-rn** [nandorojo/solito#276]
<img width="819" alt="Screenshot 2022-12-11 at 2 04 54 PM" src="https://user-images.githubusercontent.com/36214945/206931553-f6b8d4fb-ee2b-4882-a2af-47c9dbe35e5e.png">

This is the error that Vercel gives.

**Comment by nandorojo** [comment]
please try mode 16
