### ISSUE TITLE
Clone and deploy to Vercel produces 404 output

### ISSUE THREAD

**Issue by vxncetxn** [nandorojo/solito#28]
I tried the clone and deploy and even though it builds properly, the resultant website shows a 404: [https://test-solito.vercel.app/](https://test-solito.vercel.app/).

Checking the output for the deployment in the Vercel dashboard, I see that the output somehow isn't actually the build folder:
![404-output](https://user-images.githubusercontent.com/34748962/159004802-99eec710-4665-4fdf-9741-73c5d3fe858e.png)

**Comment by nandorojo** [comment]
Oh yeah I think we need to fix the deploy button on that screen. Which button did you click?

Can you go in the project settings and make sure it’s `apps/next` as the root, and that it’s marked as a Next.js app?

**Comment by vxncetxn** [comment]
I actually tried it with both the button in [https://solito.dev/starter](https://solito.dev/starter) and [https://github.com/nandorojo/solito/tree/master/example-monorepos/blank](https://github.com/nandorojo/solito/tree/master/example-monorepos/blank).

The project settings show `apps/next` as the root but does not mark it as a Next.js app (it is Others by default). I tried changing Others to Next.js manually and now it works!

**Comment by nandorojo** [comment]
I see, so the framework needs to be set to Next.js. Weird that it isn’t auto detecting that. I’ll ask Vercel. Thanks!

**Comment by nandorojo** [comment]
I asked about this here: https://twitter.com/fernandotherojo/status/1504807335000096768?s=21

**Comment by vxncetxn** [comment]
Just some further info that might help on Vercel's end: I think that the Next.js auto-detection is not working because it tries to detect the framework from the root directory of the Github repository (/) instead of the root directory that is provided (apps/next).

When I added Next.js to the package.json of the root directory of the repository (which is not correct obviously since its a monorepo), Vercel was able to properly detect Next.js and shows this in the output build logs `Detected Next.js version: 12.1.0`.

**Comment by nandorojo** [comment]
Good to know. So it seems like their auto detection is wrong for monorepos.

**Comment by nandorojo** [comment]
It's fixed!
