### ISSUE TITLE
Cannot navigate to index "/" using Solito Links

### ISSUE THREAD

**Issue by bombillazo** [nandorojo/solito#281]
I am using Expo Router for my linking/routes with Solito, and using any Solito Link component with the `href` route to an index routes like "/" will not resolve the index files, and logs the following error:

```sh
Error: Failed to parse the path to a navigation state.
```

It works as expected using the `<Link />` component from 'expo-router'.

**Comment by bombillazo** [comment]
So I had skipped [step 4
](https://solito.dev/guides/new-route#4-configure-native-linking) while setting up the linking, but then I was checking the expo-router docs to see how to set up the  default NavigationContainer and it specifies setting up linking can break expo-router:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/44002321/207710025-475b4507-b3f1-4b64-98d0-eac7dd47be2d.png">

**Comment by bombillazo** [comment]
ok, so expo-router conveniently prints the linking config on app run 🙂 

```sh
linking {
  "config": {
    "screens": {
      "(app)": [Object],
      "[...404]": "*", "_sitemap":
      "_sitemap", "links": "links",
      "login": "login"
    }
  },
```

I dont see a route for "/", which should be a route with a value "". Seems like expo-router can internally reconcile these routes but seems like Solito requires them the be explicitly set in the linking config.

**Comment by nandorojo** [comment]
Hm I see. I wonder if a middleware could fix this.

**Comment by bombillazo** [comment]
@nandorojo

**UPDATE**! 

I think I found the issue, I was using the expo-router starter that was using old versions of both ER and Solito 😖 . With the most recent versions, this is working like a charm! Closing as no issue.
