### ISSUE TITLE
Bump metro resolution in expo-router start

### ISSUE THREAD

**Issue by yuripaoloni** [nandorojo/solito#288]
The root `package.json` should be upgraded with the following `resolutions` to avoid issues with [non-posix paths] (https://github.com/expo/router/issues/13) in Windows.

```json
  "resolutions": {
    "metro": "^0.73.1",
    "metro-resolver": "^0.73.1"
  },
```

**Comment by nandorojo** [comment]
PRs welcome

**Comment by yuripaoloni** [comment]
PR #289 created
