### ISSUE TITLE
with-tailwind Starter repo fails to deploy on vercel

### ISSUE THREAD

**Issue by Jkroeger123** [nandorojo/solito#299]
Using the "Deploy" button on the Solito with Tailwind starter repo found [here](https://solito.dev/tailwind), the deployment fails with the following error:

`Error: The file "/vercel/path0/apps/next/.next/routes-manifest.json" couldn't be found. This is normally caused by a misconfiguration in your project.`

I believe turbo may be causing the issue as it seems 0 tasks are found by it's build command (as seen in the attached log.)

[log.txt](https://github.com/nandorojo/solito/files/10439029/log.txt)

**Comment by nandorojo** [comment]
i’ve heard of this issue, will have to look when i have time. thanks!

**Comment by Jkroeger123** [comment]
great thanks! It is currently a blocker on a project so I'll be digging into this as well, will update here if I find anything!

**Comment by nandorojo** [comment]
yeah i imagine. what about local `next build`?

**Comment by Jkroeger123** [comment]
`next build` works fine, it looks like the issue is `npx turbo run build --filter=next...` that runs in vercel. This filter is looking for a workspace called 'next', however in the repo the next project is named 'next-app'. Changing the project name to 'next' seems to fix the issue, although I wonder why the turbo filter changed all of a sudden? Looking at my deployment history turbo used to correctly filter, running the command `npx turbo run build --filter={./apps/next}...`

**Comment by nandorojo** [comment]
they maybe previously looked at folder names? or maybe someone in a PR got this wrong. could you PR a fix by filtering for next-app?

**Comment by nandorojo** [comment]
oh wait, is this build script auto configured by vercel?

**Comment by Jkroeger123** [comment]
Yes I believe it is auto configured, so I think we'd really only be able to rename the next workspace on our side. Although I am starting to think there is a deeper root cause then a messed up filter.

I've been getting very strange build errors on Vercel, requests timing out, etc. (For example I just tried to deploy solito-with-nativewind again and the deployment failed with `Error: error:0308010C:digital envelope routines::unsupported`)

Luckily I was able to get some green builds yesterday which unblocked me, although I'm keen on figuring out what's going on here so it doesn't block anyone else (for me the starter repo still doesn't deploy)

**Comment by nandorojo** [comment]
I know how to fix that. Give me a few

**Comment by nandorojo** [comment]
Try the following:

**Builid command:** `cd ../.. && npx turbo run build --filter=next-app`
**Node Version:** `16.x`

**Comment by Jkroeger123** [comment]
That did it, thanks! Specifically switching node versions is what did the trick. Do you think it's necessary to specify a node version in the package.json?

**Comment by nandorojo** [comment]
yeah i’ll probably specify an engine there. vercel doesn’t seem to let us configure this via the deploy button, but maybe it’s an option in vercel.json?

**Comment by Jkroeger123** [comment]
looking at the vercel docs [here](https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/node-js), it looks like this should work, although I am getting an incompatible module error, digging further into the nuances here ill update soon

**Comment by anthonyshew** [comment]
@Jkroeger123 In a monorepo, you will want to set the engines in the `package.json` of the app itself rather than the monorepo root. 👍

**Comment by Jkroeger123** [comment]
ah yup that did it thanks @anthonyshew ! I'll get a PR up with this fix
