### ISSUE TITLE
Is Solito production ready for a new app?

### ISSUE THREAD

**Issue by Tobjoern** [nandorojo/solito#300]
We are currently planning a new app, the specifications will be quite similar to beatgig.com (great app + web-app which shows very similar content), obviously we don't want to create the same components twice, but would like to reuse as many as possible.
Would you say Solito is production ready for a new app?
If not, what way would you recommend to share components between next.js and react native?

Thanks a lot for this library!

**Comment by nandorojo** [comment]
speaking from my own experience, certainly! showtime is a production app for you to use as an example, they’re open source

**Comment by Tobjoern** [comment]
Thanks a lot!
Are there other open source apps build on solito?
