### ISSUE TITLE
Update starter apps to fix image loading issues

### ISSUE THREAD

**Issue by justinmann** [nandorojo/solito#303]
withImage & withPlugins no longer work.

I modified my next.config.js to this and it seemed to work:
const { withExpo } = require('@expo/next-adapter')
const withTM = require('next-transpile-modules')([
  'solito',
  'moti',
  'nativewind',
  'app',
])
const withFonts = require('next-fonts')

/** @type {import('next').NextConfig} */
const nextConfig = {
  // reanimated (and thus, Moti) doesn't work with strict mode currently...
  // https://github.com/nandorojo/moti/issues/224
  // https://github.com/necolas/react-native-web/pull/2330
  // https://github.com/nandorojo/moti/issues/224
  // once that gets fixed, set this back to true
  reactStrictMode: false,
  experimental: {
    forceSwcTransforms: true,
    swcPlugins: [[require.resolve('./plugins/swc_plugin_reanimated.wasm')]],
  },
}

const plugins = [withTM, withFonts, withExpo]

module.exports = () => {
  return plugins.reduce((acc, plugin) => plugin(acc), {
    ...nextConfig,
  })
}

console.log(module.exports())

**Comment by nandorojo** [comment]
can you see my latest update and try that?
