### ISSUE TITLE
Document resizeMode is required and define how to use it 

### ISSUE THREAD

**Issue by justinmann** [nandorojo/solito#304]
If you are going to require resizeMode please include this property in the documentation:
https://github.com/nandorojo/solito/blob/9324f974b2d8e1f50875fd928c3f17f601cf1716/src/image/expo/image.web.tsx#L14

**Comment by nandorojo** [comment]
It’s not required. It’s on the React Native docs.

**Comment by justinmann** [comment]
Understood, but the examples in the tutorial do not include this property. So, when you copy the sample code from the website it generates warnings.
