### ISSUE TITLE
[Feature Request] Next.js `app` directory compatibility

### ISSUE THREAD

**Issue by bombillazo** [nandorojo/solito#309]
Next.js is working on [a new paradigm](https://beta.nextjs.org/docs/getting-started) for apps called the `app` directory which brings upgrades such as page grouping, sharable layouts, and other nice features. It also changes the routing approach though.

I'm not sure how big of a lift it would be but it would be great if Solito worked with the new app approach so one can use the new features. I know SSR will probably be a huge effort but using `use client` directive one could avoid trying to port SSR functionality and focus more on the new routing and page structure benefits.

**Comment by nandorojo** [comment]
see #290
