### ISSUE TITLE
TypeError: undefined is not a function (near '...(0, _react.useSyncExternalStore)...')

### ISSUE THREAD

**Issue by joseito-terence** [nandorojo/solito#310]
I'm using solito-image as below but results in error:

```
<SolitoImage
     src={product?.image}
     accessibilityLabel={product.title}
     resizeMode={'contain'}
 />
```

```
TypeError: undefined is not a function (near '...(0, _react.useSyncExternalStore)...')

This error is located at:
    in SolitoFastImage (created by CellRenderer)
    in RCTView (created by View)
    in View (created by Pressable)
    in Pressable (created by Pressable)
    in LinkCore (created by Link)
    in Link (created by CellRenderer)
    in RCTView (created by View)
    in View (created by Dripsy.View)
    in Dripsy.View (created by CellRenderer)
    in RCTView (created by View)
    in View (created by CellRenderer)
    in RCTView (created by View)
    in View (created by CellRenderer)
    in VirtualizedListCellContextProvider (created by CellRenderer)
    in CellRenderer (created by VirtualizedList)
    in RCTView (created by View)
    in View (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by VirtualizedList)
    in VirtualizedListContextProvider (created by VirtualizedList)
    in VirtualizedList (created by FlatList)
    in FlatList (created by HomeScreen)
    in RCTView (created by View)
    in View (created by Dripsy.View)
    in Dripsy.View (created by HomeScreen)
    in HomeScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by SceneView)
    in RCTView (created by View)
    in View (created by DebugContainer)
    in DebugContainer (created by MaybeNestedStack)
    in MaybeNestedStack (created by SceneView)
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by Screen)
    in MaybeFreeze (created by Screen)
    in Screen (created by SceneView)
    in SceneView (created by NativeStackViewInner)
    in RNSScreenStack (created by ScreenStack)
    in ScreenStack (created by NativeStackViewInner)
    in NativeStackViewInner (created by NativeStackView)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by NativeStackView)
    in NativeStackView (created by NativeStackNavigator)
    in Unknown (created by NativeStackNavigator)
    in NativeStackNavigator (created by NativeNavigation)
    in NativeNavigation (created by App)
    in BreakpointIndexProvider (created by DripsyProvider)
    in DripsyProvider (created by Dripsy)
    in Dripsy (created by Provider)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by NavigationProvider)
    in NavigationProvider (created by Provider)
    in Unknown (created by Provider)
    in Provider (created by App)
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
```
![WhatsApp Image 2023-01-22 at 12 25 34 PM](https://user-images.githubusercontent.com/74445627/213904437-7956ff6c-4fbc-4f08-aa01-b12de086947f.jpeg)

**Comment by joseito-terence** [comment]
here's my repo if needed.
https://github.com/joseito-terence/universal-fake-store/tree/feature/solito-image

and SolitoImage is used in the following file:
https://github.com/joseito-terence/universal-fake-store/blob/feature/solito-image/packages/app/features/home/screen.tsx

**Comment by joseito-terence** [comment]
my next.js app build is also failing after adding using SolitoImage. Works in development but build fails with following error: -

```
$ next build
info  - Checking validity of types  
info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc.json" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /home/joseito/Documents/projects/universal-fake-store/apps/next/.babelrc.json
info  - Creating an optimized production build  
warn  - Compiled with warnings

../../node_modules/react-native-fast-image/dist/index.js
Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index' (imported as 'requireNativeComponent').

Import trace for requested module:
../../packages/app/features/product/screen.tsx
./pages/product/[id].tsx


> Build error occurred
TypeError: reactNative.requireNativeComponent is not a function
    at Object.4089 (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/chunks/52.js:9:4379)
    at __webpack_require__ (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/webpack-runtime.js:25:42)
    at Object.5383 (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:41:17)
    at __webpack_require__ (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:271:39)
    at /home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:272:97
    at Function.__webpack_require__.X (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/webpack-runtime.js:108:21)
    at /home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:272:47
    at Object.<anonymous> (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:275:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  type: 'TypeError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nandorojo** [comment]
you need next 13 and react/react-dom 18.2

**Comment by nandorojo** [comment]
> my next.js app build is also failing after adding using SolitoImage. Works in development but build fails with following error: -
> 
> ```
> $ next build
> info  - Checking validity of types  
> info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc.json" https://nextjs.org/docs/messages/swc-disabled
> info  - Using external babel configuration from /home/joseito/Documents/projects/universal-fake-store/apps/next/.babelrc.json
> info  - Creating an optimized production build  
> warn  - Compiled with warnings
> 
> ../../node_modules/react-native-fast-image/dist/index.js
> Attempted import error: 'requireNativeComponent' is not exported from 'react-native-web/dist/index' (imported as 'requireNativeComponent').
> 
> Import trace for requested module:
> ../../packages/app/features/product/screen.tsx
> ./pages/product/[id].tsx
> 
> 
> > Build error occurred
> TypeError: reactNative.requireNativeComponent is not a function
>     at Object.4089 (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/chunks/52.js:9:4379)
>     at __webpack_require__ (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/webpack-runtime.js:25:42)
>     at Object.5383 (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:41:17)
>     at __webpack_require__ (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/webpack-runtime.js:25:42)
>     at __webpack_exec__ (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:271:39)
>     at /home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:272:97
>     at Function.__webpack_require__.X (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/webpack-runtime.js:108:21)
>     at /home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:272:47
>     at Object.<anonymous> (/home/joseito/Documents/projects/universal-fake-store/apps/next/.next/server/pages/product/[id].js:275:3)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14) {
>   type: 'TypeError'
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```

Hmm this makes me think your Webpack setup is wrong somehow, since it's not aliasing properly.

**Comment by nandorojo** [comment]
Closing since your example is pretty outdated version-wise (sorry, Next and Expo upgrade versions aggressively and things get deprecated). Be sure to run `expo upgrade` in `apps/expo`, then use a resolution to set react & `react-dom` to `18.2.0` in the root of your monorepo. Also, you'll need to upgrade Next.js.
