### ISSUE TITLE
Got NativeWind/tailwind working with babel plugins

### ISSUE THREAD

**Issue by Gregoirevda** [nandorojo/solito#317]
There's no need for the extra `styled` wrapper work  (`const View = styled(NativeView)`)

You can have the babel plugin working on expo I think without any additions besides Nativewind expo/bare RN setup.
For it to work on NextJS, changing the `next.config.js` to

```javascript
const nextConfig = {
//...

webpack: config => {
  config.module.rules.push({
      test: /\.(ts|tsx)$/,
      exclude: /node_modules/,
      use: {
        loader: 'babel-loader',
        options: {
          configFile: path.resolve(__dirname, '.babelrc'),
          babelrcRoots: ['../*'],
        },
      },
    });
  return config;
  }
}
```

requires `yarn add -D babel-loader`

This will apply your `.babelrc` on `next` directory and imports from `../packages`

**Comment by nandorojo** [comment]
Thanks for sharing.

It's generally a good practice to wrap UI elements anyway in your own design system. That way, you can always intercept your own logic.

Also, in order to keep plugins optional and maintain support with SWC (recommended by Next.js), I'll retain the current suggestion.
