### ISSUE TITLE
Next config not respecting pageExtensions option

### ISSUE THREAD

**Issue by jcamden** [nandorojo/solito#318]
On latest master, blank example, the `pageExtensions` next config option is not respected. For example, after adding
```
const nextConfig = {
...
  pageExtensions: ['page.tsx'],
...
}
```
pages/index.tsx et al are still recognized as pages. Conversely, if any of those files are renamed with a .page.tsx extension, they are not recognized as pages. 

I suspect that `pageExtensions` is getting overridden somehow with the `withPlugins` logic, but I'm not clear on this. If so, could it be possible to override the override? Please let me know if there is any other info that I can provide!

**Comment by nandorojo** [comment]
Not sure if there's much I can do here honestly, not familiar with that property. I would be surprised if it's getting fully overridden, but maybe there's a way for you to inspect the final config output.
