### ISSUE TITLE
SolitoImage type error if not entering all of the properties

### ISSUE THREAD

**Issue by chen-rn** [nandorojo/solito#319]
Error
![Screenshot 2023-01-27 at 3 16 47 PM](https://user-images.githubusercontent.com/36214945/215223596-a3e0e0ee-c180-4bc8-9e5b-5c28d3671f16.png)

No error
![Screenshot 2023-01-27 at 3 20 31 PM](https://user-images.githubusercontent.com/36214945/215224001-92fc473a-5b6d-48ca-9965-2c7c7effa1ed.png)

Any idea what this could be caused by?

**Comment by nandorojo** [comment]
are you on the latest version?

**Comment by chen-rn** [comment]
"solito": "^2.1.3"?

**Comment by nandorojo** [comment]
that’s weird. which next version?

**Comment by chen-rn** [comment]
"next": "^13.1.1"

**Comment by nandorojo** [comment]
what if you pass `image as number`

**Comment by chen-rn** [comment]
![Screenshot 2023-01-27 at 3 46 36 PM](https://user-images.githubusercontent.com/36214945/215226395-94f1f0be-6216-4346-92fa-9507d7cf1a32.png)
doesn't seem to fix it

**Comment by nandorojo** [comment]
<img width="211" alt="Screenshot 2023-01-27 at 6 44 23 PM" src="https://user-images.githubusercontent.com/13172299/215226496-b7530365-6df5-48b3-b2db-0d325e84e0ee.png">

Weird, this works for me.

What does `yarn why solito` give you

**Comment by chen-rn** [comment]
![Screenshot 2023-01-27 at 3 49 00 PM](https://user-images.githubusercontent.com/36214945/215226635-9dcfb147-d0fe-4b67-bad5-3e0aa0744443.png)

**Comment by chen-rn** [comment]
Hmmm, could be some thing to do with my set up. I'll just declare all the props for now and look into it later!

**Comment by nandorojo** [comment]
weird. hope it gets fixed.

**Comment by chen-rn** [comment]
ill leave a comment if i do end up figuring it out!
