### ISSUE TITLE
Expo build of app created with create-solito-app is a blank screen

### ISSUE THREAD

**Issue by gabrielEloy** [nandorojo/solito#32]
Hey, Fernando thanks for the work on solito and all the react-native-web ecosystem! Great work man!

I've been playing around with a `create-solito-app` application. During the dev workflow everything worked like a charm, but, when I tried to build my application, the expo build just spits an app which just render a blank screen. The 'nextjs' build works fine tough

I've tried generating the build both by using expo legacy build, with the command:

`expo build:android`

and with eas, by using:

`eas build`

and configuring eas to build an apk, so I could test it locally.

both build commands were run from inside the expo folder.

Both methods ended in the same result, a successfully generated apk that renders a blank screen and nothing else: 

![image](https://user-images.githubusercontent.com/37480915/160444737-4b688568-5933-444c-8348-83feb0a3a6fb.png)

So I wondered, maybe I did something wrong in my application and decided to test if I could generate a working build from a fresh, unmodified `create-solito-app`, and the build generated from it only rendered a blank page as well.

Are there any extra steps I need to take before generating my build? or is simply running the regular build commands supposed to work ?

**Comment by nandorojo** [comment]
Are there any errors in the logs?

**Comment by gabrielEloy** [comment]
I've tried using `expo run:android` and got the following error message: 

<img width="371" alt="image" src="https://user-images.githubusercontent.com/37480915/160453751-9f51d0ec-fd4a-48ed-a2eb-a18cdbf91c41.png">

and when I tried running `expo run:ios`, I got the exact same error: 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/37480915/160455773-5bab5104-f2e6-4267-b2ac-3fcc18f5a8d2.png">

**Comment by gabrielEloy** [comment]
I manage to get rid of both error messages using `expo run:<platform>` after installing `react-native-safe-area-context` and `react-native-screens`, so the app worked as expected with expo `expo run:<platform>`.

**but** when I try to generate a build using `expo build:android` it still generates an apk that renders a blank screen when opened.

I'm still generating a build with `eas build`

**Comment by nandorojo** [comment]
Hmm interesting, did `expo build` get fixed by installing those 2 packages?

**Comment by nandorojo** [comment]
`react-native-safe-area-context` (I hate typing that name out) is already installed, but RN Screens isn't, so I'll add that to the starter monorepo.

**Comment by gabrielEloy** [comment]
> Hmm interesting, did `expo build` get fixed by installing those 2 packages?

Unfortunately not. I'm still not able to generate a functional build :( 

`expo build` generates an application that when opened shows nothing more than a blank screen 

https://user-images.githubusercontent.com/37480915/160510233-defaee67-c770-41d8-a487-795797162691.mp4

I've tried using Logcat to see if I could find out more about the error and the displayed message was the following: 

`2022-03-28 19:33:08.149 11268-11268/? E/e: Failed to clear legacy OkHttp cache`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37480915/160511718-c183de30-66dd-4d88-8695-e7b00ee7642f.png">

**apparently** this is the error that is preventing my app from rendering and keeping it stuck in a white screen state

I'm still trying to figure out how to solve this error. Have you ever seen anything like it ?

**Comment by nandorojo** [comment]
What happens if you export a single view in App.tsx and don’t import anything else?

**Comment by nandorojo** [comment]
Oh whoops I didn’t realize it was a fix lol. Thank you for sending! I’ll take a look at this in the morning.

**Comment by nandorojo** [comment]
merged all the PRs, thanks for the help here @gabrielEloy! appreciate you digging in and finding the fix.

**Comment by conor909** [comment]
@gabrielEloy where are you running `eas build` from?  When I run it in the project folder and from the repo root I get:
```
It looks like you haven't initialized the git repository yet.
EAS Build requires you to use a git repository for your project.
```
