### ISSUE TITLE
Getting next-transpile-modules error on fresh install

### ISSUE THREAD

**Issue by justinireland** [nandorojo/solito#320]
I just bootstrapped a fresh tailwind monorepo and when I run `yarn web` I'm getting:

`Error: next-transpile-modules - an unexpected error happened when trying to resolve "app". Are you sure the name of the module you are trying to transpile is correct, and it has a package.json with a "main" or an "exports" field?`

`Error: Can't resolve 'app\package.json'`

**Comment by nandorojo** [comment]
Weird, does this still happen?

**Comment by corysimmons** [comment]
@justinireland What version of Next.js are you using? If 13, it _might_ be because they bundled next-transpile-modules as part of core Next.js—maybe the explicit `require('next-transpile-modules')` is conflicting with their core implementation.
