### ISSUE TITLE
Access current path from Solito Router.

### ISSUE THREAD

**Issue by KwehDev** [nandorojo/solito#321]
Hello,

We have a configuration where we display a Stack Screen for Mobile if a particular route is active.

On Web, we accomplish this with standard URL navigation.

Is it possible to get the currently active route from Solito Router? Think `window.location.pathname` but cross platform.

Thanks

**Comment by nandorojo** [comment]
Yeah, this has been discussed many times in the past. There isn't a reliable way to do this with a safe API. However, it probably makes sense to create a doc for the possible ways to do it, such as with Expo Router, or escape hatches without it.

For reference, you can see what showtime did: https://github.com/showtime-xyz/showtime-frontend/blob/3b52e71c2cb6accac4aedbde30d0d13485079214/packages/design-system/router/use-router.ts

**Comment by nandorojo** [comment]
Closing out for now, but I'll dedicate a doc to this in the future.
