### ISSUE TITLE
[Feature request] Add a way to access to the whole list of parameters

### ISSUE THREAD

**Issue by valeriobelli** [nandorojo/solito#323]
Hello! 👋

The way `solito` exposes parameters to the React tree is pretty interesting, simple as

```javascript
const { useParam, useUpdateParams } = createParam()

const FooComponent = () => {
  const [fooParam] = useParam('foo')

  ...
}
``` 

However, I noticed it does not expose ways to retrieve all the parameters simultaneously. Going straight to the code, I'm talking about

```javascript
const useParams = createParams()

const FooComponent = () => {
  const { foo } = useParams()

  ...
}
```

which would be handy when:
- we are not interested in picking a specific param, but the entire set: this would be extremely useful when a screen is dependent on many params, avoiding so to access every single parameter with a call to `useParam`;
- there are unknown or hardly typeable parameters that we want to access
  For example, the search string on the web is an excellent place to store data pieces. If we put query parameters with a UUID as a key, this would be impossible to type in typescript. The situation would be even more challenging in case the UUID represents a key of an object-like data structure, like `?foo[4faf73da-b6ef-4808-b53e-c999a5372aef]=bar&foo[2af22232-1156-44d3-a46d-cfc9594e1dc6]=baz`
- a third-party developer wants the freedom to create abstractions just on top of the parameters list' 

Is it something planned to be introduced, or is it out of the scope of this library's responsibilities?

**Comment by nandorojo** [comment]
sounds like a fair use case
