### ISSUE TITLE
SolitoImage not caching on android

### ISSUE THREAD

**Issue by Ipicon** [nandorojo/solito#324]
don't know the behavior on IOS.
but I have an endpoint in the `api` folder which serves an image (for testing),
on the web it requests once and then it caches, but on android it never caches and always goes the the specified uri.

I've tried everything for 2 days even adding cache control headers to the api, and nothing.
the native `Image` tag does cache tho....

the code on the client:
![image](https://user-images.githubusercontent.com/43734511/216773580-292bcab4-81b1-48c3-acdb-c3e6c03b589d.png)

the api:
![image](https://user-images.githubusercontent.com/43734511/216773572-b6cd59ca-409d-412a-bf18-609844e44139.png)

**Comment by nandorojo** [comment]
must be a RN fast image quirk. I’ll once expo image is released we’ll use that, which should fix it

**Comment by Ipicon** [comment]
I think expo image is just not a available in expo go but can be used in prod/dev build, same ass react-native-fast-image

**Comment by nandorojo** [comment]
it’ll be in the next SDK

**Comment by Ipicon** [comment]
I'm filled with excitement :)

**Comment by voody2506** [comment]
@nandorojo Hi, can we use expo image's https://blurha.sh feature in the next release?

**Comment by nandorojo** [comment]
yeah once it's stable in the next SDK

**Comment by xinha-sh** [comment]
> yeah once it's stable in the next SDK

1.0 has been released

**Comment by nandorojo** [comment]
v3 uses expo image, could you try that?

https://github.com/nandorojo/solito/releases/tag/v3.0.0
