### ISSUE TITLE
createParam seems to be bundling Next.js in native app

### ISSUE THREAD

**Issue by criszz77** [nandorojo/solito#325]
Hello! 

Thank you for the work you put in around the React Native community! Really an inspiration.

I'm maintaining this template: https://github.com/criszz77/luna

What I'm trying to achieve is a React Native + Next.js in one app, no monorepo. In my opinion the monorepo adds a lot of complexity and a number of fairly new React Native developers stumble across this while working with Solito for their first time.

I'm playing around with [`processModuleFilter` from Metro bundler](https://facebook.github.io/metro/docs/configuration/#processmodulefilter) which helps us discard specific modules from the output. Of course, I'm trying to discard `Next.js` from native and here are the results:

1. Either clone `🌘 Luna` or install a new app with 
<pre>npx react-native init <b>MyAppName</b> --template @criszz77/luna</pre>

2. Copy this `serializer` option in your `metro.config.js`:
```javascript
module.exports = {
  transformer: {
    ...
  },
  serializer: {
    processModuleFilter: module => {
      console.log('module', module);
      return !module.path.includes('/node_modules/next/');
    },
  },
};
```

3. Run `yarn start && yarn ios`

3. In the console.logs, not only you will see that `Next.js` seems to be bundled in the Native app, but also the app will crash.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/55203625/216788094-47decfbb-8dd0-44b4-8d0e-4dec539dd279.png">

### EDIT:

Or if you try to use Solito in a bare react native app:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/55203625/217764785-f314edd1-96d2-4df6-8497-3a66f5951a13.png">

**Comment by nandorojo** [comment]
Should be fixed in 2.2.0: https://github.com/nandorojo/solito/releases/tag/v2.2.0
