### ISSUE TITLE
 SyntaxError: Unexpected token 'export' Jest/typescript Solito  

### ISSUE THREAD

**Issue by StavKxDesign** [nandorojo/solito#333]
Hi,
 I am trying to do some Unit/integration testing with RNTL and RTL  but any component I used from Solito I experience an issue shown in the screenshot below.
Tried most of the recommendations from jest docs and looked around the web (transformIgnorePatterns, moduleNameMapper ... ) but no success I was wondering if any of you have experienced it before and resolved it somehow?

![Screenshot 2023-02-20 at 21 34 26](https://user-images.githubusercontent.com/110095257/220201636-f35882e3-5085-4c8e-8571-0bbf50b9e6dc.png)

I think I might be missing some small configuration somewhere.

Project is same setup with https://github.com/nandorojo/solito-test and implemented jest in the packages/app directory

Thanks in advance.

**Comment by derek-primumco** [comment]
I often get a similar error with Next router, so maybe this package could help: https://www.npmjs.com/package/next-router-mock#jest-configuration

Or you could try mocking it out directly ala https://dev.to/peterlidee/how-to-mock-next-router-with-jest-3p6b

**Comment by StavKxDesign** [comment]
Thanks @derek-primumco, for the recommendation about  the router, sounds sensible. 
But I need to use the UI components for example Solito/Link that can be used in Native or Web apps. 

Screenshot:
![Screenshot 2023-02-21 at 17 50 38](https://user-images.githubusercontent.com/110095257/220421862-53cbd2eb-66d0-41d9-a0d8-25e659442684.png)

I hope that makes sense

**Comment by derek-primumco** [comment]
It does make sense. Once you start digging into this stuff, I realized that Next.js doesn't try especially hard to support Jest + React Testing Library, which is a shame.

If you look at https://github.com/scottrippey/next-router-mock#compatibility-with-nextlink you'll see some notes on how to mock out `next/link`, which you should be able to adapt to SolitoLink.

You will almost certainly have to create a mock somewhere that keeps the original SolitoLink file from being read by Jest.

Here's another example mocking next/link with a stub that doesn't do anything: https://stackoverflow.com/questions/71254835/jest-testing-link-next-link

**Comment by StavKxDesign** [comment]
Thanks for the useful information @derek-primumco, I think these mocks will help me further down the line when testing routers for Next.js and Native apps pulling the shared code I am trying to test now. 

What I am trying to achieve is in my packages/app directory to have common pages or components that are reused for web and native. 
I have made my Jest performing platform agnostic tests by using  React Native and React Testing libraries depending on what platform the tests are running (IOS,Android, Web).

Now these packages/app directory components use the solito/Link and probably will use "useRouter" hook provided by the same library, haven't decided yet, I am just on trial and error stage to see what fits my requirements. we are trying solito for compatibility with expo-router for native and next-router which you mentioned above.

I am trying to avoid mocking the actual UI component that I want to render in jsdom or ReactInstance for these tests, probably will start mocking for specific frameworks in the apps/native or apps/web folder. 

It looks to me that jest doesn't even recognise or transform this module to pull in the test dom. That is why I have a suspicion that it might be a configuration solution, but might be wrong.

**Comment by derek-primumco** [comment]
Thanks @StavKxDesign, that's very interesting. I totally hear you about not wanting to mock components. But I have done Jest testing of Next.js apps a couple of times and find myself usually needing to mock `next/router`, `next/link`, or both.

Here's an example from my personal profile:
https://github.com/DoctorDerek/phonebook-filter-by-age/blob/main/__tests__/test-utils.tsx

In some cases, you can in fact get things to work correctly with `transpileModules` (`transformIgnorePatterns` and `moduleNameMapper ` in Jest) and adjusting the `jest.setup.js` file, but it depends on the case and can be difficult.

Using mocks for just the breaking component (`solito/link`) can unlock your component testing, like https://github.com/DoctorDerek/phonebook-filter-by-age/blob/main/__tests__/components/ContactCard.test.tsx in the same example app.

And my guess is that you're running into this Solito-specific issue (`solito/link`) because of ongoing issues with `next/link` not supporting Jest; see https://github.com/vercel/next.js/issues/43769 for example.

**Comment by StavKxDesign** [comment]
Thank you for your help @derek-primumco, I will try and mock the components in a platfrom agnostic way and post my solution once I am unblocked from this stage, I will keep the issue open for a bit just incase someone else has similar experiences and then close it.

**Comment by StavKxDesign** [comment]
Unfortunately for my type of implementation will not work using Solito library. 
I have tried various similar mechanisms to avoid mocking anything in the actual specific app directory
The way to test next router and links is by mocking them as you described @derek-primumco and seems to work fine for my Next application. 
I will close this issue for now, Thanks @derek-primumco
