### ISSUE TITLE
Add line to `metro.config.js` suggested for Expo monorepos

### ISSUE THREAD

**Issue by derek-primumco** [nandorojo/solito#336]
Thanks for the nice library! I'm making an issue to remind myself to submit a PR adding a line to the `metro.config.js`. This was necessary for support when adding a second Next.js library to the same monorepo using one of the Solito starter packages.

`apps/expo/metro.config.js`
```js
// 3. Force Metro to resolve (sub)dependencies only from the `nodeModulesPaths`
config.resolver.disableHierarchicalLookup = true;
```

- Here's where the line is recommended in the Expo docs:
  - https://docs.expo.dev/guides/monorepos/#modify-the-metro-config
- Affected files include all starter packages, e.g.
  - https://github.com/nandorojo/solito/blob/master/example-monorepos/with-tailwind/apps/expo/metro.config.js
- Example from Turborepo + React Native starter (Vercel)
  - https://github.com/vercel/turbo/blob/main/examples/with-react-native-web/apps/native/metro.config.js

**Comment by nandorojo** [comment]
PR welcome
