### ISSUE TITLE
Unable to resolve path to module 'react-native-safe-area-context'. `eslint(import/no-unresolved)`

### ISSUE THREAD

**Issue by derek-primumco** [nandorojo/solito#338]
# Unable to resolve path to module 'react-native-safe-area-context'. `eslint(import/no-unresolved)`

<img width="658" alt="Screenshot 2023-02-24 at 6 01 01 PM" src="https://user-images.githubusercontent.com/122907173/221323373-94883c31-1823-44aa-9697-510dcc7e294d.png">

Thoughts on this error? From `apps/expo` running `yarn add react-native-safe-area-context' fixes it, but it doesn't seem to break builds in the starter.

**Comment by nandorojo** [comment]
weird. did you run `yarn` in the root?

**Comment by derek-primumco** [comment]
Yes, that's with running `yarn` in the root. But I think the ESLint error is related to [`no-extraneous-dependencies`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) -- basically that any library you're importing from you should list as a dependency. Any reason not to do so?
