### ISSUE TITLE
Navigation error when the route has different params id

### ISSUE THREAD

**Issue by jeisux92** [nandorojo/solito#341]
Hi Fernando, i was playing around with the framework but i got a problem when navigating to a route and the params change.
for instance:
`home`=>`form/2`=>`general`=>`form/4`(this page gets override and when using `back` is going straight to `home`)

this is happening in react native and they fixed it by using a key option on the `navigation. Navigate` with something like this
```
this.props.navigation.navigate({
		routeName: 'form',
		params: { 
			id: form.id,
		},
		key: 'form' + form.id
	});
```

below a I leave a link with the reference 
https://github.com/react-navigation/react-navigation/issues/2882

**Comment by nandorojo** [comment]
does adding `getId` on your stack screen help?

**Comment by jeisux92** [comment]
yes @nandorojo , thank you so much!
