### ISSUE TITLE
trying to pass className to the Link component

### ISSUE THREAD

**Issue by sgrund14** [nandorojo/solito#342]
hello

I'm trying to pass `className` to the `Link` component (so that I can pass it a `w-fit` from tailwind). Have tried both with and without `styled` from nativewind, but the style isn't being applied on web

adding it like so: 

<img width="603" alt="Screenshot 2023-03-01 at 11 00 05 AM" src="https://user-images.githubusercontent.com/14083701/222194066-875f9876-7df4-4a0f-ad33-65a83a1ec2eb.png">

then on the browser, no tailwind class :(

![Screenshot 2023-03-01 at 11 02 16 AM](https://user-images.githubusercontent.com/14083701/222194493-a45613e2-1431-4369-b189-cad6a1e2b025.png)

is solito doing something with the `className` prop along the way?

**Comment by sgrund14** [comment]
Oh I see... I'd have to pass `viewProps`. is there a clever way to pass tailwind classes here?

**Comment by nandorojo** [comment]
This is more of a question for `nativewind`, I’m not sure the recommended way to pass styles to a prop, such as `viewProps.style` or `viewProps.className`. Or just use a wrapper view / `style` prop.
