### ISSUE TITLE
Next.js errors less useful in Solito than vanilla Next.js? (Solito Source Map)

### ISSUE THREAD

**Issue by derek-primumco** [nandorojo/solito#344]
I'm working on a Solito project, and I observed that errors in the UI seem to be the compiled jsx code instead of the TypeScript raw code.

That makes it a little harder to debug than I'm used to when working with Next.js.

Is this an inherent limitation of cross-platform development with React Native, or am I missing something obvious?

## Screenshot
![image (1)](https://user-images.githubusercontent.com/122907173/222827706-7ad082c9-29b0-4cbd-bd3b-fca7673ca419.png)

Note the `var` ... instead of the actual TSX code, which looks like:

```tsx
const {status, data, error} = useQuery( // ...
```

**Comment by nandorojo** [comment]
This is certainly not a solito-related issue. This would be related to Next.js, possibly if you're prebuilding your pages or something.
