### ISSUE TITLE
[ UseCase | FeatureRequest ] Url query parameter without name

### ISSUE THREAD

**Issue by astriskit** [nandorojo/solito#346]
This could be an edge-case, but didn't find much on handling of this sort of query-parameter in other libraries too (searched in react-navigation too). 

## Use case
In url, if the parameter is just a value. For example: `https://test.test/register?34asdf32gsdf232213ds`. 

## Handle
In this case, had to break out of solito to get the current url depending on `ReactNavigation.useRoute().path` for native/react-navigation and `window.location.pathname` for browser. And then splitting at `?` to get the last part.

## Curious
What is the opinion of the author of the library on this? Btw, this way of url making is not against the standards (per this [answer](https://stackoverflow.com/a/4557763/7986074)).

Could this be handled in solito?

**Comment by nandorojo** [comment]
Yeah this has been requested a lot, it's just a complicated thing to solve in a safe way as a library. I recommend checking out what Showtime does. If you're using Expo Router, this is solved. 

Duplicates: #10 #235 #314 #321

**Comment by astriskit** [comment]
@nandorojo  thanks for the input and pointers.👍

Btw awesome library. 🚀🎉👍
