### ISSUE TITLE
V3 typescript compatibility with Nativewind

### ISSUE THREAD

**Issue by sgrund14** [nandorojo/solito#348]
hello,

noticed that the new V3 of SolitoImage is throwing a typescript error when wrapped with `styled` from Nativewind

<img width="983" alt="Screenshot 2023-03-07 at 6 48 42 PM" src="https://user-images.githubusercontent.com/14083701/223581909-079e7c32-a3d1-4e00-b618-12a57ff6432b.png">

Seems to still be working otherwise...

**Comment by nandorojo** [comment]
This is likely a bug with the `nativewind` types. I recommend opening an issue there.

**Comment by sgrund14** [comment]
got it, although noticed that it wasn't happening on Solito V2 🤔

**Comment by sgrund14** [comment]
oh, I see. now `nativewind` wants me to be explicit about the props I pass in for some reason

```
import { styled } from 'nativewind';
import { SolitoImageProps } from 'solito/build/image/image.types';
import { SolitoImage } from 'solito/image';
export const StyledImage = styled<SolitoImageProps>(SolitoImage);
```

is required to satisfy typescript. seems like a workaround... 

fwiw, the props of the `SolitoImage` did change from V2 -> V3

V2
```
function SolitoImage(props: Omit<SolitoImageProps, 'resizeMode' | 'style'> & Pick<ComponentProps<typeof FastImage>, 'style' | 'resizeMode'>): JSX.Element
```

V3
```
const SolitoImage: ForwardRefExoticComponent<SolitoImageProps & RefAttributes<Image>>
```
