### ISSUE TITLE
How to import expo icons on web project ? 

### ISSUE THREAD

**Issue by suchcodemuchwow** [nandorojo/solito#359]
I'm getting an error when I try to import icons:

`import Ionicons from '@expo/vector-icons/Ionicons'`

Not sure how to load them and there is no documentation how to handle that in solito. Could you please enlighten ?

**Comment by nandorojo** [comment]
I would recommend not using this package honestly, it causes so many headaches and they plan to move away from it. It’s better to use a library that just uses SVG under the hood. I’ve made two of them using SVGR:

- https://github.com/nandorojo/react-native-heroicons
- https://github.com/nandorojo/react-native-iconic

It would be simple to do the same with Ionicons if you want to.

**Comment by suchcodemuchwow** [comment]
Tried to add your heroicons package which doesn't work out of the box with the solito tailwind template gives bunch of import export errors, I believe it's related to es modules, not sure where to fix in template since it has bunch of different configs.

```
export * from '../../lib/module/24/outline'
^^^^^^

SyntaxError: Unexpected token 'export'
```

I tried to install only on root and also platform specific neither of them worked.

**Comment by nandorojo** [comment]
you need to add it to next transpile modules.

**Comment by suchcodemuchwow** [comment]
Ohhh great thanks a lot 🥳

**Comment by Jonatthu** [comment]
@nandorojo Where I confirm the plans where vector icons are going away?

**Comment by nandorojo** [comment]
it's just something i heard from the team being tossed around. but in my experience, SVG-based icon libraries are far, far better
