### ISSUE TITLE
fonts in NextJS - You may need an appropriate loader to handle this file type,

### ISSUE THREAD

**Issue by rodbs** [nandorojo/solito#36]
I'm using dripsy following this guide to load fonts using `useFonts`.
https://snack.expo.dev/@nandorojo/dripsy-custom-fonts

It works on React Native, but not in web

I'm getting this error: 
```
wait  - compiling...
error - ../../packages/app/provider/assets/fonts/Inter/Inter-Bold.ttf 
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders   
(Source code omitted for this binary file)
```

I understand NextJs is not loading the fonts.

I've used this `next-fonts` package  , but I cannot make it work.
https://docs.expo.dev/guides/using-nextjs/#font-support

```

module.exports = withPlugins(
  [withTM, [withExpo, [withFonts(), { projectRoot: __dirname }]]],
  nextConfig
)
```

Is this the way to share fonts between React Native and NextJs? For images, is it the same process with` next- images`. thx!

**Comment by nandorojo** [comment]
your next config isn’t a proper array. withFonts should go before withExpo’s array.

**Comment by rodbs** [comment]
Like this ? why? I'm getting the same error:

```
module.exports = withPlugins(
  [withTM, [withFonts , [withExpo, { projectRoot: __dirname }]]],
  nextConfig
)
```


In the doc says :
```
const { withExpo } = require('@expo/next-adapter');
const withFonts = require('next-fonts');

module.exports = withExpo(
  withFonts({
    projectRoot: __dirname,
  })
);
```

**Comment by nandorojo** [comment]
No, the first one is still wrong.

```js
module.exports = withPlugins(
  [withTM, withFonts, withImages, [withExpo, { projectRoot: __dirname }]],
  {
    // ...
  }
)
```

**Comment by rodbs** [comment]
Ok, thanks

**Comment by nandorojo** [comment]
useFonts is only meant to run on the native app, are you using it on Web?

**Comment by rodbs** [comment]
yeap, i'm trying to use for web (nextJS) (using the same code for both native and web)
Should I split the code and load it on web in other way? which way do you recommend?

**Comment by nandorojo** [comment]
yeah, see the bottom of the dripsy instructions for Web. you should use `link` to load fonts in on web, just like any website.

**Comment by danieloi** [comment]
This might help

https://github.com/expo/google-fonts/issues/5#issue-655161265

**Comment by nandorojo** [comment]
Hey guys, I added a full example for using custom fonts with Solito [here](https://github.com/nandorojo/solito/tree/master/example-monorepos/with-custom-font).

```sh
npx create-solito-app@latest my-solito-app -t with-custom-font
```
