### ISSUE TITLE
Some dependencies are incompatible with the installed expo version

### ISSUE THREAD

**Issue by jmcmullen** [nandorojo/solito#360]
I've just created a new project from the tailwind starter template and I get the following error:

```
Some dependencies are incompatible with the installed expo version:
  react-native@0.71.3 - expected version: 0.71.4
  react-native-reanimated@3.0.0 - expected version: ~2.14.4
Your project may not work correctly until you install the correct versions of the packages.
Install individual packages by running npx expo install react-native@0.71.4 react-native-reanimated@~2.14.4
```

If I run the suggested `npx expo install react-native@0.71.4 react-native-reanimated@~2.14.4` command from `apps/expo`, expo go crashes as soon as I attempt to open the app inside the simulator for iOS.

Really keen to give Solito a go, any ideas what could be causing this?

**Comment by nandorojo** [comment]
we’re using reanimated 3 now, so you need to build the expo dev client instead of expo go. you can ignore those expo warnings if you do that

**Comment by jmcmullen** [comment]
Hey, thanks for the super fast reply. 

I've created a dev build and now get the error: 
```
iOS Bundling failed 4ms
Unable to resolve "expo-router/entry" from "index.js"
```

Seems to be getting called from:
```ts
import { registerRootComponent } from 'expo'
```

Using expo 48.0.0 & expo-dev-client 2.1.6.

**Comment by KaivG** [comment]
I had the same problem, may be useful to add this information to the readme. I tried to use the expo dev client and found these steps that I followed:

1. Set up an EAS account
2. Run npm install -g eas-cli
3. In the project root dir, run eas build:configure
4. Run eas build --profile development --platform android

But then my build fails with this error:
[Reanimated] Unable to resolve react-native location in node_modules. You should project extension property (in app/build.gradle) `REACT_NATIVE_NODE_MODULES_DIR` with path to react-native.

Is there maybe a guide how to go about this?

**Comment by nandorojo** [comment]
does ios work? i only tested ios

**Comment by nandorojo** [comment]
you should run eas commands in apps/expo, not in the solito root

**Comment by KaivG** [comment]
After trying around for a bit, I got it to work following your instructions in the release notes: https://github.com/nandorojo/solito/releases/tag/v3.1.1 and by changing the gradle distributionUrl in apps\expo\android\gradle\wrapper\gradle-wrapper.properties to `distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.1-all.zip`
