### ISSUE TITLE
Expo Go iOS crashes on app open for solito with expo router example

### ISSUE THREAD

**Issue by rickdotta** [nandorojo/solito#365]
I don't see any errors on the expo cli, just a bunch of ios bundling completes:

Logs for your project will appear below. Press Ctrl+C to exit.
iOS Bundling complete 501ms
iOS Bundling complete 24651ms

but when trying to open the app on expo go ios, it downloads things, and then immediately crashes.

Expo go is at the latest version, 2.28.7.

The next website is loading properly, links work.

**Comment by nandorojo** [comment]
please see the release notes. you need to use an expo dev client
