### ISSUE TITLE
TextLink doesn't display the "title" attribute properly on the web

### ISSUE THREAD

**Issue by SunnyAureliusRichard** [nandorojo/solito#367]
I'm using solito and I'm trying to set the title attribute on a TextLink which should display in next.

To replicate, try this code:

```

    <TextLink
      href="https://google.com"
      title="Go to google">
      Google
    </TextLink>
```

The result is:
```
<a href="/" dir="auto" class="css-text-1rynq56 r-userSelect-lrvibr">Google</a>
```
It should be:

```
<a href="/" title="Go to google" dir="auto" class="css-text-1rynq56 r-userSelect-lrvibr">Google</a>
```

**Comment by nandorojo** [comment]
Interesting, is there a corresponding accessibility prop in React Native Web for mapping to `title`?

**Comment by SunnyAureliusRichard** [comment]
> Interesting, is there a corresponding accessibility prop in React Native Web for mapping to `title`?

I haven't seen anything of the sorts.

**Comment by nandorojo** [comment]
Maybe ask on the `react-native-web` repo what the best way is to do this?

**Comment by nandorojo** [comment]
Is `viewProps={{ accessibilityLabel: '...' }}` what you want?
