### ISSUE TITLE
Local Preview File Images Not Showing (file:///*) On React Native

### ISSUE THREAD

**Issue by stoickeyboard** [nandorojo/solito#368]
First of all, thanks for creating Solito. You're a godsend!

I have logic where I'm previewing images before uploading using `ImagePicker` which returns the path where the temporary image is stored. Both `expo-image` and  RN image show the image just fine but `SolitoImage` seems to not like the `file:///*` path. I temporary added a loader that just returns the url if the image is local. Maybe we can add logic to not modify the src if it contains `file:///`?

**Comment by nandorojo** [comment]
without `unoptimized`, solito will apply the loader function you defined, so this behavior seems expected

**Comment by nandorojo** [comment]
perhaps we could omit the loader if the pathname is a `file://` though

**Comment by nandorojo** [comment]
just pushed `3.0.1` which ignores src props starting with `file://`

**Comment by stoickeyboard** [comment]
Just tested. All good 👍
