### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by clayrisser** [nandorojo/solito#378]
Does this support svgs?

If not, is it on the roadmap?

I have an experiment cross platform image component that also handles svgs. Feel free to take or reference any code from there.

https://gitlab.com/risserlabs/multiplatform.one/ui/-/blob/main/ui/src/images/SimpleImage/index.tsx

**Comment by nandorojo** [comment]
That's incorrect actually, `SolitoImage` does indeed support SVG on all platforms. I do recommend using `react-native-svg` over this option, but it's still possible if you need to render an SVG as an image for some reason.

In `next.config.js`:

```ts
module.exports = {
  images: {
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },
}
```

Read more on the Next docs: https://nextjs.org/docs/api-reference/next/image#dangerously-allow-svg

**Comment by clayrisser** [comment]
Ah I see. I assumed it was using the Image component from react-native (which does not support svg images). But looks like it's using expo-image which apparently does support svg images. This is great news! Thank you @nandorojo.
