### ISSUE TITLE
Expo Go doesn't work with --router template

### ISSUE THREAD

**Issue by algoflows** [nandorojo/solito#384]
Tried everything, can't get native up and running and working on my phone using expo go app by scanning the QR code, the app just crashes. I've tried literally everything and it's not working...

Run out of ideas.

**Comment by nandorojo** [comment]
you need to use an expo dev client, as mentioned in the release notes. expo go won’t work with reanimated 3. or you can downgrade reanimated, but it won’t work as well on web

**Comment by algoflows** [comment]
Okay thanks @nandorojo, what is the dev-client exactly? I see it as an argument to the npm run dev command, but not sure what a dev client is?

**Comment by nandorojo** [comment]
it means creating a custom Expo Go with the native code from your project

**Comment by Randall71** [comment]
> I have already and it didn't say much at all, does it mean emulators or physical devices?

look at this link
https://docs.expo.dev/develop/development-builds/introduction/

**Comment by rpostulart** [comment]
That does mean that you need a build each time to view what you have build.
This is not improving developer velocity. I am curious how you are doing that @nandorojo now?
Are you focusing on web and when it's working making a native build once in a wile?

**Comment by nandorojo** [comment]
not sure what you mean. you only need to rebuild the dev client when _native_ code changes. otherwise, you can just do over the air updates and use the local dev client with JS.

please get familiar with how this works from the expo side. they aren't very good at documenting it but it's out there

**Comment by rpostulart** [comment]
Yeah for sure, but what I mean is normally when you change react native code in the IDE it does a fast/hot refresh and I immediately see the results in expo

**Comment by nandorojo** [comment]
and what’s different here?

**Comment by rpostulart** [comment]
you need to run eas update each time to see the changes on the device, or am I wrong?

**Comment by rpostulart** [comment]
sorry you are totally right changes are seen via the local server.
