### ISSUE TITLE
Feature Req: Server Side Rendering

### ISSUE THREAD

**Issue by qalqi** [nandorojo/solito#388]
Looks like solito generates PWA with no server side rendering and no indexing

1. Visit https://punits.dev/check-server-side-rendered/
2. Insert https://example.solito.dev/ or https://beatgig.com/discover
3. We can see empty screen

Alternatively,
1. Visit https://punits.dev/check-server-side-rendered/
2. insert https://expo-twitter.netlify.app/  (https://github.com/EvanBacon/expo-router-twitter)
3. We can see server rendered content

**Comment by nandorojo** [comment]
this is the case for the dripsy example only. for SSR, you can use the tailwind example, or see tamagui’s solito starter on their docs.

**Comment by nandorojo** [comment]
It's possible I'll just remove Dripsy from the SSR example.

**Comment by qalqi** [comment]
Looks like with  "expo": "^49.0.0-alpha.3" and expo-router we can get SSR
