### ISSUE TITLE
How to use SolitoImage with blurDataURL 

### ISSUE THREAD

**Issue by AlejandroGutierrezB** [nandorojo/solito#391]
What would be the best strategy to implement blurDataURL in all platforms?

After digging seems like next/image v13> (what solito uses) only supports base64 encoded urls to produce the blur effect. While expo-image supports a blurhash string.

Therefore I need to calculate both in the BE and provide those to the app?  

I would love to see your take here @nandorojo 

Also opening this in an issue as I believe docs could have more info, let me now if this shouldn't be here. I will be happy to open a PR to expand the docs afterwards too.

**Comment by nandorojo** [comment]
it's in the docs

https://solito.dev/usage/image#blurdataurl

**Comment by nandorojo** [comment]
> After digging seems like next/image v13> (what solito uses) only supports base64 encoded urls to produce the blur effect. While expo-image supports a blurhash string.

I see, so they're different approaches? I'm not too familiar with how blur hash works.

**Comment by nandorojo** [comment]
web accepts a Data URL type: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

**Comment by AlejandroGutierrezB** [comment]
> web accepts a Data URL type: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

you will need to actually convert the remote url to a bse64 image, thus defeating the purpose of the placeholder.

I guess there is no other way than getting both strings serverside, and then doing a Platform.OS ternary to pass as the blurDataURL

**Comment by la55u** [comment]
Just guessing here but expo-image also supports thumbhash, which is base64 so in theory it should work with next image too as a placeholder? That way you'd only need to generate one for each image on your backend.

**Comment by AlejandroGutierrezB** [comment]
> Just guessing here but expo-image also supports thumbhash, which is base64 so in theory it should work with next image too as a placeholder? That way you'd only need to generate one for each image on your backend.

Indeed worked, I think it might be worth mention it in docs @nandorojo.
