### ISSUE TITLE
Unable to open solito.dev site

### ISSUE THREAD

**Issue by thenorthstar79** [nandorojo/solito#393]
- The site seems to be offline

**Comment by nandorojo** [comment]
what country is this? it works for me

**Comment by thenorthstar79** [comment]
I am trying to access it from Nigeria. Still unable to access it, both solito.dev and solito.dev/v2

**Comment by derek-primumco** [comment]
Some ISPs block Vercel -- see https://www.reddit.com/r/nextjs/comments/pl11tc/vercels_ip_is_blacklisted_and_inaccessible_from/

**Comment by nandorojo** [comment]
Sorry, I'm not exactly sure what I can do here...is there a recommended way around this for Nigeria?
