### ISSUE TITLE
`router.replace` with `stack-replace` animate screen push twice

### ISSUE THREAD

**Issue by idrakimuhamad** [nandorojo/solito#394]
When using `replace` with `nativeBehavior` and `isNestedNavigator`, the screen that replacing the current screen are seen to be push twice. Although upon going back, there's only one, but the transition unfortunately appear to be twice. Example code below.

```jsx
const router = useRouter()

  useEffect(() => {
    async function init() {
      await sleep(1000)

      router.replace("/pay/recipient-selection", undefined, {
        experimental: {
          nativeBehavior: "stack-replace",
          isNestedNavigator: true,
        },
      })
    }

    init()
  }, [])
```

The screen movement are Tab (inside a stack) -> Different Stack -> First screen -> Second Screen

As seen by the video below.

https://github.com/nandorojo/solito/assets/1400323/3eab9b8e-a6ab-4393-9db8-17007eeccc19

When using the `expo-router`, things work as expected.

https://github.com/nandorojo/solito/assets/1400323/2409b00f-3b4c-458e-8e06-3159312809b8

**Comment by nandorojo** [comment]
hmm, can you first not do this in an effect? want to make sure that’s not firing twice. it should ideally be on an event handler

**Comment by idrakimuhamad** [comment]
Yeah i've tried with `onPress` -- that's working fine.

Regular `.replace` without  `nativeBehavior` doesn't behave this way; however, it doesn't replace the previous screen probably due being nested.

**Comment by nandorojo** [comment]
isn’t this evidence that it was calling the replace function twice? you could also pass an empty dependencies array right

**Comment by idrakimuhamad** [comment]
Update: Okay the static variable doesn't work it still called twice. lol.

Yeah i send empty array and it still behaving the same. The `handleNavigate` being called twice.

What's weird is that if I replace this with just `.replace` or router from `expo-router` it doesn't behave this way.

**Comment by derek-primumco** [comment]
Are you using strict mode?

```
Since React 18, useEffect is called twice in Strict Mode when zero dependencies.
```
Source: https://github.com/facebook/react/issues/24553

**Comment by idrakimuhamad** [comment]
> Are you using strict mode?
> 
> 
> 
> > Since React 18, useEffect is called twice in Strict Mode when zero dependencies.
> 
> 
> 
> Source: https://github.com/facebook/react/issues/24553

I do not, at least I do not know specifically putting anything about it within my code. Plus, I thought the app needed to use the new architecture to React 18 features, which i haven't.

And related to that, if I were to swap the implementation directly from solito router with expo router, it doesn't trigger twice which baffle me. 😅

**Comment by nandorojo** [comment]
Yeah, that's certainly weird. Solito only fires one action. FWIW, I don't recommend ever navigating via effects. Your loading state shouldn't be a new screen, but rather just a state of the screen firing the mutation action. Once it finishes, just open the next screen.

Does calling `router.replace()` from a button press do the same thing?

**Comment by idrakimuhamad** [comment]
Calling it from event doesn't trigger it twice.

I understand effects can make this tricky, but my use case are not about loading a data -- the screen here are sort of an entry screen where it decide which screen it would go depending on the API response. As such, it needs to have "redirects" behaviour.

Also, calling replace without native stack options doesn't make the transition happening twice.

For now, I rely on expo router to do this. And separate my web entry file and use next router directly.

**Comment by nandorojo** [comment]
Got it, I wonder what’s causing it. Maybe you could pull the code from the Solito replace function and try console.logging to see where it goes wrong.

**Comment by idrakimuhamad** [comment]
After a while, I notice that the issue are not precisely solito. Although the expo-router doesn't replace the screen twice, it is indeed that the stack is re-rendered, twice. On. the first render, the screen and effect ran once. However, after moving back and into the stack again, that screen seems to be mounted twice. It seems to be mounted and unmounted and mounted again. so weird. lol.

I'll close this issue since finally, it is not a solito issue.
