### ISSUE TITLE
How to get params with Solito

### ISSUE THREAD

**Issue by danielkv** [nandorojo/solito#4]
Actually I'm writing this issue, because I want to understand the mental model you were talking about here: https://github.com/nandorojo/solito/issues/3#issuecomment-1025749315

I do understand that `NextJS` and `React Navigation` have their differences when you want to get params. `React Navigation` uses its own API `useRoute` and `NextJS` uses `getStaticProps` and etc.

Been that said I'll describe my understanding so for, using `solito`:

```tsx
// expo/router/user-route.tsx 

import UserScreen from 'screens/HomeScreen';
import { useRoute } from '@react-navigation/core';

const UserRoute: React.FC = () => {
    const [user, setUser] = useState(null);
    const { params: { userId } } = useRoute();

    useEffect(()=>{
        if (!userId) return;
        const userLoaded = await loadUserFromId(userId)
        setUser(userLoaded);
    }, [userId])
    
    if (!user) return null; // or loading
    return <UserScreen user={user} />
}

export default UserRoute;
```

```tsx
// next/pages/user/[userId].tsx

import UserScreen from 'screens/HomeScreen';

const UserPage: React.FC<{user: IUser}> = ({ user }) => {
    if (!user) return null;
    return <UserScreen user={user} />
}

export default UserPage;

export const getStaticProps = async ({params}) => {
     const userLoaded = await loadUserFromId(params.userId)

    return {
        props: { user: userLoaded }
    }
}
```

Are my thoughts correct? Or there is another way to retrieve these data?

If it's correct, I'd say it should go in **docs/receipts**. I think there are a lot of devs that have those same doubts

**Comment by nandorojo** [comment]
Reading in params is a whole different story. That hasn’t been added to the lib yet, although it wills

Here is the function I plan on adding later: https://gist.github.com/nandorojo/052887f99bb61b54845474f324aa41cc

**Comment by nandorojo** [comment]
I just added `useParam` to Solito, including docs for it!

https://solito.vercel.app/usage/params

> Great, but you think the opening comment is a good way to do it? That way we can take advange of the static generation

Yeah that's the idea, though I would use `useParam` rather than `useRoute` probably.
