### ISSUE TITLE
Some problems with Eslint and Typescript

### ISSUE THREAD

**Issue by yuriazevedo11** [nandorojo/solito#40]
Hey @nandorojo, huge fan of your work here

I've created a repo using create-solito-app yesterday, but I'm having some issues. Maybe I'm missing something, but I don't have much knowledge on monorepos

### Eslint

With Eslint, `next/` has its own .eslintrc.js. How can I extend with my own config there? I do have my own Eslint npm package. One side note, running the nextjs app was not working until I added this: 

```javascript
module.exports = {
  extends: 'next',
  root: true,
  rules: {
    '@next/next/no-html-link-for-pages': ['error', 'apps/next/pages/'],
  },
};
```
Maybe this should be in the template?

### Typescript

And with Typescript, my intellisense is a mess on Vscode. Some auto imports simply just not work.

Example: I just deleted MotiLink import from this template file, but Typescript can't find MotiLink to import
![Screen Shot 2022-04-08 at 10 48 35](https://user-images.githubusercontent.com/51724047/162448974-4e3c71fd-3578-49f6-a45c-9983d2f45f2c.png)

This was only one example, but I'm having this same problem with some other packages, depending from where I try to import them. 

Currently, I've just added some devDependencies on root, like husky, lint-staged and commitlint for example.

Can you help me out?

**Comment by nandorojo** [comment]
hey! you mentioned a number of different questions here. i’ll try to answer later today

**Comment by nandorojo** [comment]
> With Eslint, next/ has its own .eslintrc.js. How can I extend with my own config there? 

Doesn't this work?

```json
{ "extends": ["next", "your-config-here"] }
```

**Comment by yuriazevedo11** [comment]
About the Eslint, I'm having some conflicts between my config and 'next', I'll take a deeper look

What about `@next/next/no-html-link-for-pages` rule? Nextjs app wasn't running before this rule was added

About the Typescript autocomplete, let me know if you find out something 👍

**Comment by nandorojo** [comment]
What isn’t working without that rule? Building? Can you please clearly outline reproducible steps?

**Comment by yuriazevedo11** [comment]
yarn web wasn't working for me without this rule

**Comment by yuriazevedo11** [comment]
I did a clean install, removing node_modules. Seems to be working without this rule now

**Comment by nandorojo** [comment]
worked fine for me without the rule in a fresh app

**Comment by yuriazevedo11** [comment]
Yeah, I guess Eslint was my bad

I'm just missing now the Typescript autocomplete, can you reproduce this problem?

**Comment by nandorojo** [comment]
yes, and i think i found the solution

**Comment by nandorojo** [comment]
can you try upgrading solito to `0.0.25` and see if that fixes it?

**Comment by yuriazevedo11** [comment]
### It worked 🚀 

Still having this problem tho, but I guess is not a big deal:
![Screen Shot 2022-04-08 at 17 00 13](https://user-images.githubusercontent.com/51724047/162518002-883c9320-6857-41d8-91b9-bcd3299ba59b.png)

### There's still some problems for me:

This one is pretty bad, I'd like to autocomplete the screens import here
![Screen Shot 2022-04-08 at 17 03 48](https://user-images.githubusercontent.com/51724047/162518401-3cf53d15-f4df-47c6-8d8b-0543509aff3b.png)

This one is not that bad, because the imports of screens will be in `packages/app/navigation/native`
![Screen Shot 2022-04-08 at 17 04 26](https://user-images.githubusercontent.com/51724047/162518476-18db7bcd-6a66-4def-adcf-c933424ab339.png)

But inside `packages/app/navigation/native`, the autocomplete only shows `apps/next/pages`, not the `packages/app/features`

![Screen Shot 2022-04-08 at 17 09 08](https://user-images.githubusercontent.com/51724047/162519094-464fbc47-fd24-4e99-9f79-e7a26f3ba15b.png)

Do you have any clue how to fix these? Specially screenshot 2 and 4

**Comment by nandorojo** [comment]
yeah, to fix those, you’d need to install `solito` in `apps/next` too. this is a constraint of typescript monorepos. i’ve written about it here:

https://github.com/nandorojo/ts-monorepo-autoimport-guide

generally this shouldn’t matter, since almost all of your code should be written in the `app` folder. but you can solve it with the guide i linked to there

**Comment by yuriazevedo11** [comment]
Thanks! Nice guide :) 

What about screenshots 2 and 4? I really do miss these autocomplete imports from `app/*`

**Comment by nandorojo** [comment]
i don’t get screenshot 2. you’re writing export default of a variable that doesn’t exist.

**Comment by nandorojo** [comment]
for 4, don’t use the same name when exporting in next?

also, in general, use named exports, not default ones

**Comment by yuriazevedo11** [comment]
Sugestion for 4 works 🚀 . And I do use named exports only, but next/pages need export default

About screenshot 2, I can work around it. I just wanted autocomplete for the screen I'll need to use re-export in next/pages, but it does not work

Thank you so much for your help, keep up the good work :D
