### ISSUE TITLE
Strategy for client side components

### ISSUE THREAD

**Issue by sarat1669** [nandorojo/solito#402]
Is there a way to define a component as a client side rendered component?

In nextJS it's done via `next/dynamic`. Is this the recommended way?

I'm assuming I'd have to create `.web.ts` and `.native.ts` for each client side rendered component to handle this.

Backstory:
I'm using firebase token based auth and SSR is required only for the pages which need indexing.
I don't want to switch to a cookie based auth and wouldn't mind if the pages / components that require auth context are not SSR.
Looking for a better way to achieve this cross-platform apart from the one mentioned above.

**Comment by nandorojo** [comment]
next dynamic should work
