### ISSUE TITLE
useRouter missing route and asPath property

### ISSUE THREAD

**Issue by megacherry** [nandorojo/solito#406]
Hi Fernando,

i have successfully included i18next in my monorepo. When I change the language (i18n.changeLanguage), I usually execute a router.push with the current locale.

This looks like this:

```
import {useRouter} from 'solito/router'.
import {useRouter as useNRouter} from 'next/router'

...

const router = useRouter()
const nrouter = useNRouter()

...

router.push(nrouter.route, nrouter.asPath, {locale: newLang})
```

Works under NextJS, but not with solito-router because the router and asPath properties are missing.

Do you have a solution for this?

Thanks and best regards
Andy

**Comment by megacherry** [comment]
Ahh, i found this discord chat: https://discord.com/channels/1085921563372703815/1092493277762179172

seems to be related :-D

**Comment by nandorojo** [comment]
Yeah, I still need a better solution for this. I might be able to do it sometime in the next few weeks as built-in solution. Or sooner if you want to sponsor :) I'll close this for now though, can reopen later if work is resumed on it. https://github.com/sponsors/nandorojo
