### ISSUE TITLE
yarn native error in minimal setup

### ISSUE THREAD

**Issue by xementor** [nandorojo/solito#413]
[Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.0.2 vs. 2.14.4). Did you forget to re-build the app after upgr
ading react-native-reanimated? If you use Expo Go, you must downgrade to 2.14.4 which is bundled into Expo SDK.

**Comment by nandorojo** [comment]
The error message appears to give the exact solution. Make sure you upgrade all reanimated versions in your repo.

**Comment by nandorojo** [comment]
Oh, you have to use an expo dev client, not expo go. once we upgrade the starters to SDK 49 this will be fixed.

**Comment by xementor** [comment]
As I'm running the expo client that I downloaded from play store, I don't see two variations of expo.

is there any other way to get expo dev client?

**Comment by xementor** [comment]
when I upgraded to sdk 49 with `expo upgrade` is also changed other package version, so it worked for native but create problem with next or web.

But when I just changed version ^48.0.0 to ^49.0.0 in expo/package.json. now its working.

Thank you

**Comment by nandorojo** [comment]
Got it, interesting. I need to upgrade the example apps still, so sorry for any trouble there. Glad you got it sorted!
