### ISSUE TITLE
Does solito work with React Native for Mac OS?

### ISSUE THREAD

**Issue by jparismorgan** [nandorojo/solito#415]
Hi there, does solito work with React Native for Mac OS? https://github.com/microsoft/react-native-macos

**Comment by derek-primumco** [comment]
I'm not sure. I see React Native for Mac OS https://microsoft.github.io/react-native-windows/ is on React Native 0.72, which is a good sign.

But I don't see any support for Expo / Metro Bundler so you'd probably have to do some configuration yourself https://microsoft.github.io/react-native-windows/docs/rnm-getting-started

**Comment by nandorojo** [comment]
So, it should...but kind of. Solito _itself_ will as long as `react-navigation` does. That said, I don't have any examples made. You would add a `desktop` folder at `apps/desktop`, and likely you would add `workspaces.nohoist: ["apps/desktop/react-native"]` (though I'm not sure about this) to your root package.json to get it to work. I have no experience here honestly, but it would be very cool if it did work.

**Comment by jparismorgan** [comment]
Awesome, thank you! I have no experience with react-native yet, so don't think it's likely I will be able to contribute this. But if someone else gets it working I'd be happy to test it out!
