### ISSUE TITLE
Is there a way to animate SVG fill color with Moti?

### ISSUE THREAD

**Issue by derek-primumco** [nandorojo/solito#416]
Hey Fernando, thanks again for the great library.

Is there a way to combine `motifySvg` with a React Native Heroicon to animate the SVG fill color?

The following snippet using `motifySVG` will console.log() the appropriate fill color, but there's no animation of it changing.

(This snippet is the `<Child />` within a parent `<MotiPressable>`.)

```tsx
import { LinkIcon } from "react-native-heroicons/solid"
import { useMotiPressable } from "moti/interactions"
import { motifySvg } from "moti/svg"
import { forwardRef } from "react"

export default function AnimatedLinkIcon(){
  const AnimatedIcon = motifySvg(forwardRef(LinkIcon))()

  return (
    <MotiIcon
      state={useMotiPressable(({ hovered, pressed }) => {
        "worklet"

        const getFillColor = () => {
          if (disabled && fillColor?.disabled) return fillColor?.disabled
          if (pressed && fillColor?.pressed) return fillColor?.pressed
          if (hovered && fillColor?.hovered) return fillColor?.hovered
          return fillColor?.enabled
        }
        const out = {
          fill: getFillColor();
        }
        console.log(out)
        return out
      })}
      transition={{
        type: "timing",
        duration: 150,
      }}
    />
  )
}
```

**Comment by nandorojo** [comment]
hey, so i think you’d have to copy the source of the icon you want and make its relevant components animated…

**Comment by nandorojo** [comment]
also, never call motifySvg inside the component like your example. that’s terrible for performance

**Comment by derek-primumco** [comment]
OK, thanks! I'll see what I can get working by motifying the relevant pieces of the component.
