### ISSUE TITLE
Custom Fonts with Solito

### ISSUE THREAD

**Issue by iyifr** [nandorojo/solito#421]
I get this error using font files in solito with dripsy and expo fonts.
../../packages/app/assets/fonts/BebasNeue-Regular.ttf
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
Any help / tips ?

**Comment by iyifr** [comment]
The error occurs on web (next js)

**Comment by nandorojo** [comment]
can you remove next-fonts from your next config if it’s there

**Comment by iyifr** [comment]
Should i move my fonts folder away from packages/app

**Comment by iyifr** [comment]
Oh yeahhh , okay.
I'll try it out and give an update

**Comment by iyifr** [comment]
How does integrate with dripsy?

**Comment by iyifr** [comment]
It doesnt seem to work

**Comment by nandorojo** [comment]
sorry i know the docs for custom font could be better

could you reference this example and tell me if it works?

https://github.com/nandorojo/solito/tree/master/example-monorepos/with-custom-font

**Comment by iyifr** [comment]
I did that , it loads the font properly now
It would be awesome if you added it to the recipes ,something like "Handling fonts on web"

**Comment by iyifr** [comment]
I mean the recipes on solito

**Comment by nandorojo** [comment]
yeah agreed

**Comment by nandorojo** [comment]
i’ll leave this open for now

**Comment by iyifr** [comment]
Thanks for the fast responses man

**Comment by afu-hive** [comment]
If you your font at google
Here my code in solito using google font and it's work fine both expo & next

```typescript
// packages/app/provider/index.tsx
import {
  useFonts,
  Sarabun_200ExtraLight,
  Sarabun_400Regular,
  Sarabun_600SemiBold,
} from '@expo-google-fonts/dev' // using dev for all font in google
import AppLoading from 'expo-app-loading'

export function Provider({ children }: { children: React.ReactNode }) {
    const [fontsLoaded] = useFonts({
       Sarabun_200ExtraLight,
       Sarabun_400Regular,
       Sarabun_600SemiBold,
    })

     if (!fontsLoaded) return <AppLoading />
     
    return (...)
}
```

**Comment by nandorojo** [comment]
that code should only run on native, as it should use css font loading on web instead

**Comment by nandorojo** [comment]
going to close this and will add a recipe in the future for font loading, ideally with next-font
