### ISSUE TITLE
tailwind intellisense inside the tailwind tempalte

### ISSUE THREAD

**Issue by Ipicon** [nandorojo/solito#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

when using the tailwind example from the starters (both old and new), there's no intellisens for tailwind inside the `packages/app` components.

that's because the tailwind intellisense plugin (either VScode or WebStorm) needs a `tailwind.config.js` file at the root of the "workspace".

### Expected Behavior

full tailwind intellisense inside the `packages/app` folder, due to being the main directory we code at.

a quick fix for that is to put a "dummy" tailwind config file either at the root of the project or at the root of `packages/app`.
don't mind opening a PR if it's worth "fixing".

### Versions

```markdown
- Solito:
- Next.js:
- Expo:
- React Native:
```

**Comment by derek-primumco** [comment]
Yes, I've seen this issue as well. Like you said, adding the root workspace `tailwind.config.js` file will fix it, though I'd love to see if anyone has any other thoughts on the topic.

```js
// tailwind.config.js
// Dummy file to enable Tailwind CSS Intellisense
module.exports = require("./packages/app/tailwind.config.js") // Relative path to real config file
```

I originally found this solution here: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/345#issuecomment-896412228.

**Comment by nandorojo** [comment]
Interesting, I don't use tailwind so I can't offer much help here. I thought you could customize this somewhere but I'm not sure

**Comment by Ipicon** [comment]
All we need to do is add the dummy file, you mind if I open a PR about it?

**Comment by nandorojo** [comment]
Go for it!
