### ISSUE TITLE
docs: Sidebar not opening in mobile browser

### ISSUE THREAD

**Issue by arielvieira** [nandorojo/solito#430]
### Is there an existing issue for this?
- [X] I have searched the existing issues

### Do you want this issue prioritized?
- [X] Not urgent

### Current Behavior
Sidebar is not opening when in a mobile browser.

### Expected Behavior
Sidebar should open when in a mobile browser

### Steps To Reproduce
1. Open https://solito.dev website in a mobile device
2. Try to open the sidebar menu 

### Screenshots
![image](https://github.com/nandorojo/solito/assets/17505779/29f7210a-5b7a-4d47-a591-f80f3520b5c6)
![image](https://github.com/nandorojo/solito/assets/17505779/b82ce9dd-6a79-4003-a6f0-0473bab4cf1d)

### Reproduction
There's might be related to the beta version docusaurus, maybe upgrading it to a stable version would fix the issue.
https://github.com/nandorojo/solito/blob/d31260b0685e6ab5b942bb6f67c72ab6184704a0/docs/package.json#L17

**Comment by nandorojo** [comment]
would accept a pr fixing this, i think it might be an issue in the custom css

**Comment by arielvieira** [comment]
> would accept a pr fixing this, i think it might be an issue in the custom css

I found the issue, it is due to the `navbar--fixed-top` class with `backdrop-filter` property that breaks the position absolute. I'll open a PR to fix this.

Reference: https://stackoverflow.com/questions/52937708/why-does-applying-a-css-filter-on-the-parent-break-the-child-positioning 

https://github.com/nandorojo/solito/blob/a86a352b5b7eda1e453f84505b51bfaac23f3635/docs/src/css/custom.css#L134
