### ISSUE TITLE
twrnc - Cannot use import statement outside a module

### ISSUE THREAD

**Issue by eduluq** [nandorojo/solito#44]
Hey! 

I'm getting this error when trying to import twrnc (https://github.com/jaredh159/tailwind-react-native-classnames) in my solito app.

```
Server Error
SyntaxError: Cannot use import statement outside a module
```

I've installed both like this
```
npx create-solito-app@latest my-solito-app
cd packages/app
yarn add twrnc
```

But then when trying to import it in any of my components
```
import tw from 'twrnc'

function HelloWorld() {
  return (
    <View style={tw`bg-blue-100`}>
      <Text style={tw.style('text-md')}>Hello</Text>
    </View>
  )
}
```

I get the error
`SyntaxError: Cannot use import statement outside a module`

Any ideas on how to fix this?
Thanks!

**Comment by nandorojo** [comment]
you need to add it to next-transpile-modules in next confits

**Comment by eduluq** [comment]
> you need to add it to next-transpile-modules in next config.

Working. Thanks @nandorojo!

**Comment by nandorojo** [comment]
no problem! they should probably add it to their nextjs docs
