### ISSUE TITLE
 Error Running React Native Skia in Solito Repo: Can't Resolve 'react-native-reanimated/package.json'

### ISSUE THREAD

**Issue by alvishdml** [nandorojo/solito#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [x] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

Hello Solito community,

I'm encountering an issue while trying to run React Native Skia in the Solito repository for both mobile and web. Mobile seems to work fine, but I'm running into a problem on the web platform, which is also causing issues during the Next.js build. I hope someone can provide some guidance on resolving this issue.

```
warn ../../node_modules/@shopify/react-native-skia/lib/module/external/reanimated/moduleWrapper.js
Module not found: Can't resolve 'react-native-reanimated/package.json' in '/Users/apple/Documents/chessingly-frontend/node_modules/@shopify/react-native-skia/lib/module/external/reanimated'
```

### Expected Behavior

**Expected Behavior:**

In the context of running React Native Skia on the Solito repository with Next.js, the expected behavior should be as follows:

1. Successful Web Platform Build: When running the project on the web platform with Next.js, there should be no errors related to missing or unresolved dependencies, especially the 'react-native-reanimated/package.json' issue.

2. Compatibility with React Native Skia: React Native Skia should seamlessly integrate with the Solito repository, allowing for smooth development and use of React Native components and functionality.

3. Consistency with Mobile Platform: The behavior on the web platform should be consistent with the behavior observed on the mobile platform. Any components or functionality that work on mobile should work as expected on the web.

4. Proper Functionality: All features and interactions of the application, whether mobile or web, should function correctly without errors or issues related to the integration of React Native Skia.

By achieving these expected behaviors, the project should run smoothly and without any critical errors, making it possible to develop and deploy Solito on both mobile and web platforms.

**Note:** If there are specific additional behaviors or outcomes you expect, please feel free to elaborate on them.

### Versions

```markdown
- Solito: 4.0.1
- Next.js: 13.4.19
- Expo: 49.0.0
- React Native: 0.72.4
- react-native-reanimated: 3.3.0
- @shopify/react-native-skia: 0.1.208
```

**Comment by nandorojo** [comment]
Not totally sure what's going on. Might be a skia issue?
