### ISSUE TITLE
className and id props are not getting passed to the anchor tag when using solito/link

### ISSUE THREAD

**Issue by xinha-sh** [nandorojo/solito#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

```tsx
<SolitoLink
  href={`/shop/products/${product.slug}`}
  id={`ph-link-product-${product.slug}`}
>
```
```html
<a href="/shop/products/slug-abcd">...</a>
```
Workaround for ID

```tsx
<SolitoLink
  href={`/shop/products/${product.slug}`}
  viewProps={{
    id: `ph-link-product-${product.slug}`
  }}
>
```

For ``className`` same thing happens when className props is set to Link component.  Unlike ``id``,  viewProps doesn't accept className at all.

![Screenshot 2023-11-01 at 12 50 46 PM](https://github.com/nandorojo/solito/assets/107257599/7392fb60-afec-44d9-ad8a-f6e706115916)

### Expected Behavior

```tsx
<SolitoLink
  href={`/shop/products/${product.slug}`}
  id={`ph-link-product-${product.slug}`}
>
```
```html
<a href="/shop/products/random-slug" id="ph-link-product-random-slug">...</a>
```

### Steps To Reproduce

1. Create a solito project
2. Import Link component
3. Add 
```tsx
<Link
        href="/user/fernando"
        className="abcd"
        id="abcd"
      >
        <P>Fernando</P>
      </Link>
```
4. check browser. ``className`` and ``id`` are not passed from parent element
5. Try ``viewProps``. Here you'll be able to pass ``id`` but not ``className``

### Versions

```markdown
- Solito: 4.1.3
- Next.js: 13.5.4
- Expo: 49.0.4
- React Native: 0.72.4
```

### Screenshots

https://github.com/nandorojo/solito/assets/107257599/bf4fee9a-46ab-425e-b66b-e74fa5218ef3

**Comment by xinha-sh** [comment]
> React Native Web doesn’t accept className, only the style prop. Are you using TailWind, or can I ask why you’re trying to use className instead of style?

Yup using tailwind. But I need className basically for analytics purpose

**Comment by nandorojo** [comment]
I see, does native wind offer a hook that turns this into a style prop? Or a way to map className to a nested property? I would check showtime's repo to see how they use link (it's likely wrapping the solito link).

**Comment by nandorojo** [comment]
Also how is className related to analytics?

**Comment by xinha-sh** [comment]
> Also how is className related to analytics?

I want to track clicks on link and differentiate them. Example I have a link that opens product page, another link that opens collection page. Custom click events can be distinguished using className, so I was thinking of doing that. I'm not sure if pattern matching id is an option. But that's what I'll be trying next.

**Comment by nandorojo** [comment]
I think I have a better solution. I’ll share it tomorrow.

**Comment by nandorojo** [comment]
Here's what I do:

1. Make `accessibilityLabel` **required** on my `Button` component
2. Inside of `onPress`, I do `telemetry.track(Pressed ${accessibilityLabel})`
3. Add an `analytics` prop for any additional fields to the button directly, such as `via`

```tsx
const Frame = ButtonFrame.styleable<{
  accessibilityLabel: string
  disableAnalytics?: boolean
  analytics?: { via?: string; label?: string } & Record<string, string | number> 
}>(function Frame(
  {
    size = '$3',
    unstyled = false,
    disableAnalytics,
    analytics,
    onPress,
    accessibilityLabel,
    square,
    ...props
  },
  ref
) {
  const wrapPress =
    <F extends (...a: any[]) => any>(callback?: F) =>
    (
      e: Parameters<
        NonNullable<ComponentProps<typeof ButtonFrame>['onPress']>
      >[0]
    ) => {
      callback?.(e)

      if (!disableAnalytics) {
        const capitalizeAllWords = (s: string) => {
          return s
            ?.split(' ')
            .filter(Boolean)
            .map((word) => word[0].toUpperCase() + word.slice(1))
            .join(' ')
        }

        let {
          // eslint-disable-next-line prefer-const
          label = 'Pressed ' + capitalizeAllWords(accessibilityLabel),
          ...properties
        } = analytics || {}

        properties = {
          via: 'button',
          ...properties,
          ...(e?.defaultPrevented && { defaultPrevented: 'true' }),
        }

        setTimeout(() => telemetry.track(label, properties), 10)
      }
    }
  return (
    <ButtonFrame
      onPress={onPress && wrapPress(onPress)}
      accessibilityLabel={accessibilityLabel}
```
