### ISSUE TITLE
Can't use react-native-reanimated with Expo Router Starter

### ISSUE THREAD

**Issue by hubciorz** [nandorojo/solito#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

When I try to use `useAnimatedStyle` from `react-native-reanimated` in the next.js part in a fresh installation of `npx create-solito-app@latest -t with-expo-router`, I get this error: 
```
Unhandled Runtime Error
Error: useAnimatedStyle was used without a dependency array or Babel plugin. Please explicitly pass a dependency array, or enable the Babel/SWC plugin.

For more, see the docs: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/web-support#web-without-a-babel-plugin
```

### Expected Behavior

I should be able to use it without an error.

### Steps To Reproduce

1. Create a fresh solito project with `npx create-solito-app@latest -t with-expo-router`
2. Add some component that uses `useAnimatedStyle` in `packages` folder
3. Add a corresponding screen definition in `apps/next`
4. Run `yarn web` and go to http://localhost:3000/path_to_the_screen

### Versions

```markdown
- Solito: 4.0.1
- Next.js: 13.4.19
- Expo: 49.0.0
- React Native: 0.72.2
```

### Screenshots

<img width="1326" alt="Zrzut ekranu 2023-11-19 o 23 00 54" src="https://github.com/nandorojo/solito/assets/6502822/b960eccd-2468-4856-9a87-ef99350a8905">

**Comment by nandorojo** [comment]
Not sure how much more clear the error message could be (I wrote it). It explains how to fix it.

**Comment by hubciorz** [comment]
Sorry, I was confused because the link redirects to a 404.
<img width="985" alt="image" src="https://github.com/nandorojo/solito/assets/6502822/a379dbcf-e834-4dc6-a2b1-a0a882be5f09">

**Comment by nandorojo** [comment]
Ah, they changed their docs 🤦‍♂️

**Comment by hubciorz** [comment]
Yep. It should be `https://docs.swmansion.com/react-native-reanimated/docs/guides/web-support#web-without-a-babel-plugin` instead.

**Comment by nandorojo** [comment]
Got it, would be a good upstream PR then
