### ISSUE TITLE
How to deploy solito monorepo to vercel

### ISSUE THREAD

**Issue by iyifr** [nandorojo/solito#451]
Solito no longer deploys to vercel with the turborepo set up
![image](https://github.com/nandorojo/solito/assets/105992164/fdb8062e-417b-4146-bc54-e9a06c987423)
![image](https://github.com/nandorojo/solito/assets/105992164/f1ab9a77-4a42-4eb8-8bd1-9a72f126a23b)
Type Checking fails which should be a easy fix right , just turn off strict ts in next js 
Now I have done all of that on the solito project I've been working on
![image](https://github.com/nandorojo/solito/assets/105992164/77c7a08e-5cf2-4e75-b9bd-b7495f8a8578)
I keep getting errors for the output directory after building code
![image](https://github.com/nandorojo/solito/assets/105992164/6f17c9e3-db5b-491f-ae20-9db8a276b1c2)
Even after setting the output directory in my project settings to apps/next/.next
Still no luck

**Comment by iyifr** [comment]
![image](https://github.com/nandorojo/solito/assets/105992164/8e009df8-b283-4333-82b4-5e434a93b8b9)
It builds correctly but can't get the output right

**Comment by zvndev** [comment]
Same exact issue here when deploying directly to vercel from the Solito docs: https://solito.dev/expo-router

**Comment by nandorojo** [comment]
You can just remove that comment then

**Comment by nandorojo** [comment]
Fix has been pushed
