### ISSUE TITLE
[EXPO SDK 50] [expo-head] Error: generic class 'Field' requires that 'Date' conform to 'AnyArgument'

### ISSUE THREAD

**Issue by SVronskiy** [nandorojo/solito#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

I'm using solito starter with tailwind. After upgrading to EXPO SDK 50.0.0-preview.4 and running 'yarn ios' I get an error:
```
❌  (../../node_modules/expo-head/ios/ExpoHeadModule.swift:28:6)

  26 |     @Field
  27 |     var keywords: [String]?
> 28 |     @Field
     |      ^ generic class 'Field' requires that 'Date' conform to 'AnyArgument'
  29 |     var dateModified: Date?
  30 |     @Field
  31 |     var userInfo: [String: AnyHashable]?
```
'yarn web' and 'yarn android' works fine, problem is only with ios in expo-head. Can you please help to fix it?

### Expected Behavior

It should n't be an error.

### Steps To Reproduce

Described at https://github.com/expo/expo/issues/25983

### Versions

```markdown
- Solito: 4.0.1
- Next.js: 13.4.19
- Expo: 50.0.0-preview.4
- React Native: 0.73.0

 expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 14.2
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 18.19.0 - /usr/local/opt/node@18/bin/node
      Yarn: 3.4.1 - /usr/local/bin/yarn
      npm: 10.2.3 - /usr/local/opt/node@18/bin/npm
      Watchman: 2023.12.04.00 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.12.1 - /Users/a123/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 23.2, iOS 17.2, macOS 14.2, tvOS 17.2, watchOS 10.2
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 15.1/15C65 - /usr/bin/xcodebuild
    npmGlobalPackages:
      eas-cli: 5.9.1
      expo-cli: 6.3.10
    Expo Workflow: managed
```

### Reproduction

https://github.com/SVronskiy/solito-expo-sdk50

**Comment by nandorojo** [comment]
Please open this issue with expo-router or expo-head

**Comment by SVronskiy** [comment]
According to source code problem in expo-router 2, there is no expo-head in expo-router 3. But still not able to make it work. The reason why I have to upgrade to expo sdk 50 beta - different errors in reanimated.

**Comment by nandorojo** [comment]
It’s an expo issue, not a solution one
