### ISSUE TITLE
useParam should accept arrays

### ISSUE THREAD

**Issue by pcmaffey** [nandorojo/solito#47]
In the docs for useParam, you say ``The values of Query must be primitives, such as strings/booleans/numbers, since you can't use nested fields in a URL with next router.``

However, with Next, when using optional params eg. `[...slug]`, the param is returned as an array. This is breaking typescript stuff for me when trying to use createParam/useParam.

**Comment by nandorojo** [comment]
I believe the actual implementation works for this. Would accept a PR to the docs.
