### ISSUE TITLE
TextLink does not work in Next.js app routes

### ISSUE THREAD

**Issue by lanc33llis** [nandorojo/solito#478]
This is relatively clear when looking at the [router](https://github.com/nandorojo/solito/blob/master/src/router/next-router.ts) it is using, the old page router that does not work in app routes. Causes https://nextjs.org/docs/messages/next-router-not-mounted

This isn't inherently a bug, but it could be clearer in docs that you cannot use `solito/link` at all in app routes, and that you must instead create custom link components using `solito/navigation` 

Besides changing docs, remediation could be using `next/compat/router` to check if we're in app or pages router, but that probably means rewriting `solito/link` quite a bit and makes parts of `solito/navigation` redundant

[reference](https://www.reddit.com/r/nextjs/comments/1aep6bv/comment/leiantd/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
```tsx
// not next/router here!
import { useRouter } from "next/compat/router";

export function useIsAppRouter() {
  // it returns the router instance if it is rendered in the pages router
  // returns null if it is in the app router
  const router = useRouter();
  return !router;
}
```

**Comment by nandorojo** [comment]
hmm weird, it actually should work…because it’s using `next/link` under the hood which I believe works with the app router, right?

https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating

**Comment by nandorojo** [comment]
here’s an example of Link working for me: https://github.com/nandorojo/solito/blob/master/develop/appdir/app/page.js

**Comment by nandorojo** [comment]
what is the code that broke for you?
