### ISSUE TITLE
Starter monorepo deployment fails

### ISSUE THREAD

**Issue by fobos531** [nandorojo/solito#48]
Hello,

I've tried to use deploy the starter monorepo but I'm getting this error on compile:
<img width="1041" alt="CleanShot 2022-04-14 at 12 48 08@2x" src="https://user-images.githubusercontent.com/19533289/163376549-750c6c39-4355-420e-82dd-deeba082577a.png">

I also tried to manually create a solito app locally, and I'm getting the same kind of error:
![CleanShot 2022-04-14 at 12 48 50](https://user-images.githubusercontent.com/19533289/163376654-69054751-b4ff-40d5-ab30-66d692b7663a.png)

Do you have any ideas as to what might be the issue?

**Comment by nandorojo** [comment]
that’s odd. this happens on a fresh repo? or did you upgrade to react 18?

**Comment by fobos531** [comment]
> that’s odd. this happens on a fresh repo? or did you upgrade to react 18?

On a fresh repo, when I press the vercel deploy button. When using `create-solito-app`, it happens after the command has finished executing.

**Comment by nandorojo** [comment]
i removed the lock file yesterday so that might be why.

**Comment by nandorojo** [comment]
can you do `yarn why @types/react-native`

**Comment by fobos531** [comment]
> yarn why @types/react-native

```yarn why v1.22.18
[1/4] 🤔  Why do we have the module "@types/react-native"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/react-native@0.67.4"
info Has been hoisted to "@types/react-native"
info Reasons this module exists
   - "workspace-aggregator-59eea0f8-6596-49ee-a5e5-0eafbe4be990" depends on it
   - Specified in "devDependencies"
   - Hoisted from "_project_#@types#react-native"
info Disk size without dependencies: "600KB"
info Disk size with unique dependencies: "784KB"
info Disk size with transitive dependencies: "1.96MB"
info Number of shared dependencies: 4
=> Found "expo-app#@types/react-native@0.64.24"
info This module exists because "_project_#expo-app" depends on it.
info Disk size without dependencies: "604KB"
info Disk size with unique dependencies: "788KB"
info Disk size with transitive dependencies: "1.96MB"
info Number of shared dependencies: 4
✨  Done in 0.61s.```

**Comment by nandorojo** [comment]
I’ll revert the yarn lock changes later today if I have some time. You can copy it from the commits if you’d like.

**Comment by fobos531** [comment]
Yep, that seems to have done the trick. Thank you very much!

**Comment by nandorojo** [comment]
I believe I just pushed the fix!

**Comment by wibb36** [comment]
If one happens to upgrade to react 18, you'll most likely run into this issue since react native is depending on the latest `@types/react` and you end up with two different versions in your monorepo. To be safe, in the root package.json, add `"resolutions": { "@types/react": "version you're using in apps/expo" }`.

To check run: `yarn why @types/react` or check your yarn.lock file.
