### ISSUE TITLE
Storybook.js Support

### ISSUE THREAD

**Issue by jalexw** [nandorojo/solito#49]
I am hoping to use [Storybook.js](https://storybook.js.org/) to build a component library for a Solito app I am building. Has anyone tried to install Storybook.js into a Solito project with success? The Storybook.js CLI currently does not have Solito as an installation option and I am unsure of whether it is best to manually set up Storybook.js stories in the `apps/next`, `apps/expo` or `packages/app` folders.

Would love to hear your thoughts on creating a Solito preset in the Storybook.js CLI or your experience installing it in an existing Solito app!

**Comment by nandorojo** [comment]
I know @axeldelafosse has an example repo with storybook/expo/next

**Comment by axeldelafosse** [comment]
Yeah! Here it is: https://github.com/axeldelafosse/storybook-rnw-monorepo

**Comment by dohomi** [comment]
The example seems to be outdated because without any additional steps Storybook breaks due to missing router context. 
```
Uncaught Error: NextRouter was not mounted.
```
To fix this `storybook-addon-next-router` comes to a rescue

**Comment by nandorojo** [comment]
You’ll need to upgrade to the latest version of solito

**Comment by dohomi** [comment]
Even with 2.1.3 I need to add `storybook-addon-next-router` into my Storybook environment.
