### ISSUE TITLE
Starter blank repo gives error: "Module not found: Can't resolve 'react-native'"

### ISSUE THREAD

**Issue by that-one-arab** [nandorojo/solito#501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [ ] Not urgent

### Current Behavior

Installing the starter blank monorepo using command `npx create-solito-app@latest my-solito-app` gives error
```
Module not found: Can't resolve 'react-native'
> 1 | import { PixelRatio, Platform } from 'react-native';
    | ^
  2 |
  3 | export function rem(value: number): number | string {
  4 |   if (Platform.OS === 'web') return `${value}rem`;

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
../../node_modules/@expo/html-elements/build/elements/Headings.js
../../node_modules/@expo/html-elements/build/Elements.js
../../node_modules/dripsy/build/core/components/H1.js
../../node_modules/dripsy/build/core/components/index.js
../../node_modules/dripsy/build/core/index.js
../../node_modules/dripsy/build/index.js
../../packages/app/features/home/screen.tsx
./pages/index.tsx
 ⨯ ../../node_modules/@expo/html-elements/build/css/units.js:1:1

```

### Expected Behavior

It should work without errors

### Steps To Reproduce

1. Install the monorepo with command `npx create-solito-app@latest my-solito-app`
2. cd into the project then run `yarn web`
3. Go to localhost:3000

### Versions

```markdown
- Solito:
- Next.js:
- Expo:
- React Native:
```

**Comment by devAbreu** [comment]
I am experiencing same problems with dependencies when using Yarn 4.1.1 in a Solito based project. Attached is the log showing the warnings and problems encountered during installation:

I'm using `npx create-solito-app@latest my-solito-app`

```bash
➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @react-navigation/native-stack@npm:7.0.0, @react-navigation/native@npm:7.0.0, solito@npm:4.3.0, @react-navigation/core@npm:7.1.0, and 9 more.
➤ YN0085: │ - @react-navigation/core@npm:6.4.9, @react-navigation/elements@npm:1.3.18, @react-navigation/native-stack@npm:6.9.13, @react-navigation/native@npm:6.1.7, and 4 more.
➤ YN0000: └ Completed in 1s 64ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ @react-navigation/native is listed by your project with version 7.0.0, which doesn't satisfy what @react-navigation/native-stack (p258ae) and other dependencies request (^7.0.7).
➤ YN0060: │ next is listed by your project with version 14.2.11, which doesn't satisfy what @expo/next-adapter (pdeaf5) requests (^13.0.0).
➤ YN0002: │ app@workspace:packages/app doesn't provide react (p473ad), requested by @react-navigation/native.
➤ YN0002: │ app@workspace:packages/app doesn't provide react (p96e0e), requested by @react-navigation/native-stack.
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native (p508b9), requested by @react-navigation/native.
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native (p851e7), requested by @react-navigation/native-stack.
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native-reanimated (pe7eec), requested by moti.
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native-safe-area-context (p132cb), requested by @react-navigation/native-stack.
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native-screens (p11884), requested by @react-navigation/native-stack.
➤ YN0002: │ next-app@workspace:apps/next doesn't provide eslint (p29e84), requested by eslint-config-next.
➤ YN0002: │ next-app@workspace:apps/next doesn't provide expo (p8f46e), requested by @expo/next-adapter.
➤ YN0002: │ next-app@workspace:apps/next doesn't provide react (p2df79), requested by @expo/next-adapter.
➤ YN0002: │ next-app@workspace:apps/next doesn't provide react (p47822), requested by next.
➤ YN0002: │ next-app@workspace:apps/next doesn't provide react-dom (p8185c), requested by next.
➤ YN0002: │ next-app@workspace:apps/next doesn't provide react-native-web (p9df76), requested by @expo/next-adapter.
➤ YN0002: │ next-app@workspace:apps/next doesn't provide webpack (pa5629), requested by @expo/next-adapter.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 1182 packages were added to the project (+ 212.8 MiB).
➤ YN0000: └ Completed in 0s 366ms
➤ YN0000: ┌ Link step
➤ YN0007: │ turbo@npm:1.8.3 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 5s 507ms
➤ YN0000: · Done with warnings in 7s 38ms
```

### Highlighted issues
Version conflicts:

@react-navigation/native is at version 7.0.0, but other dependencies like @react-navigation/native-stack require ^7.0.7.
next is at version 14.2.11, but @expo/next-adapter requires ^13.0.0.
Unmet dependencies: There are multiple dependencies that are not installed in the packages inside the workspaces, such as react, react-native, react-native-reanimated, among others.

Peer dependencies warning: Yarn suggests running yarn explain peer-requirements <hash> to get more details about the conflicts.

I am using Yarn workspaces in a project that includes applications as packages/app and apps/next, following the structure recommended by Solito. I tried to fix the problems by adjusting the versions and adding the missing dependencies, but the problems persist.

Are there specific recommendations for resolving these caveats or a suggested approach for handling conflicts between @expo/next-adapter, @react-navigation, and react/next version dependencies?

**Comment by nandorojo** [comment]
Technically we should be removing all react navigation dependencies if expo-router is also installed as of the latest version of expo router

**Comment by nandorojo** [comment]
I think I need to get rid of expo HTML elements. If you remove those from the page it should get fixed. I need to simplify the starter to handle this

**Comment by garyThrels** [comment]
Anything we can do to help here, as without the starter theres very little information out there on how a new project can be started

**Comment by krisbaum74** [comment]
+1. Module not found: Can't resolve 'react-native'

**Comment by ditorahard** [comment]
+1

**Comment by CarlosMion** [comment]
+1

**Comment by AlexTr** [comment]
+1

**Comment by gabohc** [comment]
Probably an unwanted solution, but in the meantime, using yarn 1.22.22 worked for me:

```
# ... Change the version and wait for it to install
yarn set version 1.22.22


# ... then install dependencies
yarn

# ... et voilà
yarn web
```

**Comment by nandorojo** [comment]
Fixed: https://github.com/nandorojo/solito/commit/ff4bd78ceb70962532314b31bac8f662f4ec2696

Please try again now. Will re-open if it persists. Appears to have been an issue with newer Yarn workspaces versions, thanks to @gabohc for the tip.

**Comment by clemensmol** [comment]
I still have this (typescript only) issue.

```
Cannot find module 'react-native' or its corresponding type declarations.
```

**Comment by nandorojo** [comment]
Under what conditions? In a new starter? Did you apply the above changes?

**Comment by nandorojo** [comment]
Brand new starter released with Next.js 15 and more! See the release notes here: https://github.com/nandorojo/solito/releases/tag/v4.4.0

```sh
npx create-solito-app@latest
```

That should work now, please let me know if it's not. Thanks!
