### ISSUE TITLE
useParam: implement setParams on native

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/solito#51]
currently, the behavior on iOS/Android is to start with the screen parameter, and then use react state after that. this doesn't make much sense. we should use react navigation params the whole time, by using `setParams` under the hood.

**Comment by sleekLancelot** [comment]
Hi Fernando.
As this been solved?
Currently testing my app on andriod. And when using params, it only uses the first one selected. Routing to that page still returns the same param even with a different slug.
But all works as expected on web.
 I use "solito": "latest"

**Comment by nandorojo** [comment]
hey, not quite yet. i know the solution but haven’t had time to fix it with work

**Comment by sleekLancelot** [comment]
Alright, thanks man!

**Comment by nandorojo** [comment]
You can test this now on `0.0.29-alpha.1`:

`yarn add solito@canary`
