### ISSUE TITLE
is deep linking supported by this package?

### ISSUE THREAD

**Issue by louisholley** [nandorojo/solito#53]
hey - we're starting a new cross-platform project soon and solito looks perfect for the job! I noticed that the [deep linking section on the docs](https://solito.dev/recipes/deep-linking) is just a placeholder, is that because this isn't possible yet or that it's just not documented yet? we'll definitely need deep linking capabilities which is why I'm enquiring before we get started

thanks so much!

**Comment by nandorojo** [comment]
yes, it is possible! just follow the guide on react navigation’s docs for linking, and then configure your app for universal linking. you’ll need to add a file to your next.js app, referenced as the apple app site association.

**Comment by louisholley** [comment]
amazing, thanks so much @nandorojo !

**Comment by nandorojo** [comment]
I wrote up the [guide here](https://solito.dev/recipes/deep-linking).

**Comment by louisholley** [comment]
you hero, thank you @nandorojo !!
