### ISSUE TITLE
useRouter back: Doesn't work in a component which is between the NavigationContainer and Navigators (native)

### ISSUE THREAD

**Issue by MEggersZA** [nandorojo/solito#58]
I have a navigation manager component using Solito instantiated between the NavigationContainer and the Navigators.

Using back() from useRouter does not work at this level as navigation is not defined when back runs in use-router.js

The reason for this is the current code uses navigation context as below in the useNavigation hook

```
import { NavigationContext } from '@react-navigation/core'
import { useContext } from 'react'

export const useNavigation = () => useContext(NavigationContext)
```

Is there a reason not to change it to be like the code (lifted from their source) in react navigation's useNavigation hook. ie to fall back to using the NavigationContainerRefContext as below?  

```
import { NavigationContext, NavigationContainerRefContext } from '@react-navigation/core';
import { useContext } from 'react';
export const useNavigation = () => {
   const root = useContext(NavigationContainerRefContext);
   const navigation = useContext(NavigationContext);

   if (navigation === undefined && root === undefined) {
      throw new Error("Couldn't find a navigation object. Is your component inside NavigationContainer?");
    } // FIXME: Figure out a better way to do this
  
  
    return navigation !== null && navigation !== void 0 ? navigation : root;
}
```
appreciate any input.

@nandorojo  Absolutely loving this library by the way. So handy. Thanks a million for your work

**Comment by nandorojo** [comment]
I’d accept a PR to fix this

**Comment by MEggersZA** [comment]
Great, thanks Fernando. I have opened one. PR #60
