### ISSUE TITLE
Metro encountered an error resolving next/router, Haste package next was found  However the module `router` could not be found within the package

### ISSUE THREAD

**Issue by danielolamide** [nandorojo/solito#71]
this error is thrown in the ```apps/expo```  when I import ```createParam``` in ```packages/app```. How do I give ```packages/app``` access to my next package in the ```apps/next``` node modules?

**Comment by nandorojo** [comment]
hey, are you using the starter monorepo? there isn't much info for me to help here

**Comment by danielolamide** [comment]
hey sorry, this was my mistake, i wasn't using the starter-monorepo and forgot to change the package name of my nextjs app from ```next``` to something else e.g ```nextjs-app```
