### ISSUE TITLE
Monorepo issue with dependencies transpilation

### ISSUE THREAD

**Issue by MiguelNiblock** [nandorojo/solito#74]
hi @nandorojo I was trying out your solito starter, and it's really cool. Found an ugly issue though. The reference to "app" in the next/package.json is being understood by yarn as a reference to this "app". https://www.npmjs.com/package/app What you're really intending to do is reference the local package "packages/app". So it's actually installing that other library inside the node_modules of the "next" app.
Monorepos are super weird, many people use them and miss tiny details like this. I'm trying to avoid them now, they're so hard to control 100%.
How did I discover this? I was examining the peerDependencies of various packages, for example, run  `npm view @expo/next-adapter@"^3" peerDependencies` and I saw it actually depends on next v11. I also need next 11 for compatibility with AWS Amplify. So I downgraded to next@"^11", and the next app stopped working. The error message I got is.

```
error - ../../packages/app/provider/index.tsx
Module parse failed: Unexpected token (4:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { NavigationProvider } from './navigation'
| 
> export function Provider({ children }: { children: React.ReactNode }) {
|   return (
|     <NavigationProvider>
```
So that basically is saying that the app module isn't getting transpiled. So I then checked next.config.js, and it IS listed there under "next-transpile-modules". However, I think that reference is for the "app" in the next/node_modules, which is the one from npm, not the local "packages/app". I think for this to work correctly you need to either install the local "app" into the "next/node_modules", or make that code be transpiled by default, making it part of the next source. 

The other unknown is why this issue doesn't happen in next@12? Who knows. Monorepos are mysterious.

**Comment by MiguelNiblock** [comment]
![image](https://user-images.githubusercontent.com/32658920/170907184-52c22885-9007-4107-8822-13cba69e90a2.png)

**Comment by nandorojo** [comment]
the version of next transpile modules doesn't work with next 11. just use the latest next and it should work fine. you can ignore the expo peer dependency

**Comment by nandorojo** [comment]
if you are downgrading, you should match the right version of next-transpile-modules

**Comment by MiguelNiblock** [comment]
Wait, the NavigationProvider is being run on next, which means the .web. extensions aren't being resolved anymore. I'll try downgrading that too, thanks.

**Comment by nandorojo** [comment]
> see it points to some other "app" package. And it's also the one in the node_modules. Just checked.
> 
> ![image](https://user-images.githubusercontent.com/32658920/170907184-52c22885-9007-4107-8822-13cba69e90a2.png)

Is this package in your node modules folder? or is this just VSCode doing it

**Comment by MiguelNiblock** [comment]
It is actually in my node_modules. But I checked in my other copy of the same repo, before downgrading, and it was a symlink to the local "app". I can't explain why there would be such difference just after downgrading. So that means there's nothing wrong with the initial setup.

**Comment by nandorojo** [comment]
interesting. one solution would be to rename this to `@app` or related

**Comment by MiguelNiblock** [comment]
I think it happened because I accidentally ran yarn inside `apps/next`, whereas installing modules in monorepo should only be done at the rootDir. Else all the node_modules get messed up
