### ISSUE TITLE
Static images in Expo + Next

### ISSUE THREAD

**Issue by RichardLindhout** [nandorojo/solito#78]
Images are not loaded now in Next.js, I did put my images at packages/app/assets.  On NextJS it renders an empty view without any image ta
![Schermafbeelding 2022-06-02 om 23 09 35](https://user-images.githubusercontent.com/6492229/171738797-9a44a7f8-3508-454b-9d50-c3263d0e37d7.png)
g

**Comment by arjendevos** [comment]
@RichardLindhout It appears to break. 
`TypeError: unsupported file type: undefined (file: undefined)`

**Comment by louisholley** [comment]
@arjendevos i fixed this issue by passing:

```
[
      withImages,
      {
        exclude: path.resolve(__dirname, "../../node_modules/*"),
        images: {
          disableStaticImages: true,
        },
      },
    ],
```

to `withPlugins`

**Comment by nandorojo** [comment]
In general, would be useful for you guys to share full code (ie your entire next config file). It's hard to debug without that.

@louisholley thanks for sharing that

**Comment by MainStreetTech** [comment]
@louisholley, that'd be great if you could share the before and after next.config file

**Comment by louisholley** [comment]
@MainStreetTech before:

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack5: true,
};

const { withExpo } = require("@expo/next-adapter");
const withPlugins = require("next-compose-plugins");
const withFonts = require("next-fonts");
const withTM = require("next-transpile-modules")([
  "solito",
  "dripsy",
  "@dripsy/core",
  "@dripsy/gradient",
  "moti",
  "@motify/core",
  "@motify/components",
  "app",
  "react-native-web",
  "react-native-svg",
  "native-base",
]);

module.exports = withPlugins(
  [withTM, withFonts, [withExpo, { projectRoot: __dirname }]],
  nextConfig
);
```

after:
```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack5: true,
};

const path = require("path");
const { withExpo } = require("@expo/next-adapter");
const withPlugins = require("next-compose-plugins");
const withFonts = require("next-fonts");
const withImages = require("next-images");
const withTM = require("next-transpile-modules")([
  "solito",
  "dripsy",
  "@dripsy/core",
  "@dripsy/gradient",
  "moti",
  "@motify/core",
  "@motify/components",
  "app",
  "react-native-web",
  "react-native-svg",
  "native-base",
]);

module.exports = withPlugins(
  [
    withTM,
    withFonts,
    [
      withImages,
      {
        exclude: path.resolve(__dirname, "../../node_modules/*"),
        images: {
          disableStaticImages: true,
        },
      },
    ],
    [withExpo, { projectRoot: __dirname }],
  ],
  nextConfig
);
```

**Comment by nandorojo** [comment]
I have something similar, except I don’t use `images.exclude`. I also put the `images` object directly into `nextConfig`

**Comment by MainStreetTech** [comment]
@nandorojo @louisholley Thank you

This is working for me now

`
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack5: true,
}

const { withExpo } = require('@expo/next-adapter')
const withPlugins = require('next-compose-plugins')
const withImages = require('next-images')
const withTM = require('next-transpile-modules')([
  'solito',
  'dripsy',
  '@dripsy/core',
  'moti',
  '@motify/core',
  '@motify/components',
  'app',
])

module.exports = withPlugins(
  [withTM, [
    withImages,
    {
      images: {
        disableStaticImages: true,
      },
    },
  ],[withExpo, { projectRoot: __dirname }]],
  nextConfig
)
`

**Comment by nandorojo** [comment]
Hey guys, try out the new `solito/image`: https://solito.dev/usage/image

It doesn't support optimizations via `require`, only `import`. Once all images use `import` instead of `require`, you can remove `disableStaticImages: true` from your next config.
