### ISSUE TITLE
createParam not available 

### ISSUE THREAD

**Issue by tonymckendry** [nandorojo/solito#8]
I am trying to utilize the new Params functions that were added but they don't seem to be available. 
I double checked that my package was on the most recent version on NPM (0.0.22 - which says it was published an hour ago) and tried to delete/reinstall my node_modules - I can see the new Params folder inside the Solito node_modules directory as well. Is this a bug with the package or possibly something wrong on my end? 

![image](https://user-images.githubusercontent.com/15657008/157524444-ecb36752-3d9a-4614-b69b-4a676b9fd5b8.png)

**Comment by nandorojo** [comment]
hmm weird, the [example monorepo](https://github.com/nandorojo/solito/tree/master/example-monorepos/blank) is on v22 as well, and it's working [there](https://github.com/nandorojo/solito/blob/master/example-monorepos/blank/packages/app/features/user/detail-screen.tsx) for me.

**Comment by nandorojo** [comment]
I may have found it, one sec

**Comment by tonymckendry** [comment]
I also ran a super quick test where I spun up an empty repo and it seemed to work fine for me there but I am having a hell of a time upgrading my existing project for some reason.

**Comment by nandorojo** [comment]
weird, when I did it on codesandbox it worked:

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/13172299/157531721-5381f904-e2bb-4092-b87c-591e2e7f9ca6.png">

https://codesandbox.io/s/blissful-bush-8qpgvn?file=/src/index.ts

**Comment by tonymckendry** [comment]
I ended up needing to `yarn remove solito` and `yarn add solito@latest` to get it to work ultimately but it's there now.

**Comment by nandorojo** [comment]
interesting, maybe a caching issue of sorts. glad it worked
