### ISSUE TITLE
[Help Wanted] Can someone make a `create-solito-app` CLI?

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/solito#9]
I'd like to have a `create-solito-app` CLI. It can be really basic. It can read from the `example-monorepos` folder, which currently only has one option.

**Comment by luizuk** [comment]
I never made a CLI before, don't know if my knowledge is sufficient to do it, but can hear your opinion and ideas.

**Comment by nandorojo** [comment]
Thanks @luizuk! I made some good progress here: https://github.com/nandorojo/solito/tree/master/create-solito-app

I basically copied create-next-app. Besides one bug, and the ability to pick from multiple templates (once there are multiple), then I think this should be good!

**Comment by nandorojo** [comment]
Looks like I got this working after all! Thanks for offering to help @luizuk!

**Comment by nandorojo** [comment]
File is here: https://github.com/nandorojo/solito/blob/daf46806bbcd9922d1d3e8587fdb15d8c495429b/create-solito-app/index.ts

Inspiration came from `create-react-native-app` and `create-next-app` (they shared quite a bit, too)

**Comment by luizuk** [comment]
> Looks like I got this working after all! Thanks for offering to help @luizuk!

It always a pleasure can help, thanks for the library! 👏
