### ISSUE TITLE
Background color/text colors not working with Dripsy and Starter Repo

### ISSUE THREAD

**Issue by michaelangrivera** [nandorojo/solito#95]
First of all, a huge **THANK YOU** for making this framework and paving the path to more sane cross-platform development. 

I'm not sure if it's just my machine or configuration, but I've noticed the `colors` property for `makeTheme` from `drispy` does not work with the starter repository. 

Using the following code in the `dripsy` [docs](https://www.dripsy.xyz/usage/theming/color-modes) does not seem to have an affect on the `DripsyProvider` for Next:

```
import { makeTheme } from 'dripsy'
const darkColors = {
  $background: 'black',
  $text: 'white',
}
export const theme = makeTheme({
  colors: darkColors,
})
```
Inputting the hex color `#000` doesn't seem to work either. I haven't seen any discussion on dripsy theming, so please let me know if I'm missing anything solito specific. 

I'm using the repository via **Vercel** deployment button and have not made any other changes/configurations. 

My machine info (probably irrelevant):
```
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
Intel Iris Plus Graphics 1536 MB
2.3 GHz Quad-Core Intel Core i7
```

I'm still new to this framework, so hopefully, it's not _too_ stupid of a question. 

Thank you again!

**Comment by nandorojo** [comment]
hey there! have a repo you can share?

**Comment by michaelangrivera** [comment]
https://github.com/bagelhouse/solito-test-1 

This is the blank repo I was mentioning. 

https://github.com/bagelhouse/mileaday

This is the repo I'm developing my app on. It's got some extra stuff (NestJS backend and Firebase authentication), very much WIP and just started it, lol. 

Both have the same issue it seems!

**Comment by nandorojo** [comment]
![409EAFA6-DBCE-43B6-9828-5F56A7224052](https://user-images.githubusercontent.com/13172299/177050003-bb050f5a-8ff6-4e68-ac70-2af58526bef6.png)

this is what I see in your test repo, where are the colors?

**Comment by michaelangrivera** [comment]
@nandorojo sorry, the changes were local. I pushed an example.

**Comment by michaelangrivera** [comment]
Commit SHA is `fef2f3df3ed3d7c8f7f587614f266ee46d1dbba6`

**Comment by nandorojo** [comment]
and what’s the issue exactly, the colors don’t apply? where are you using it?

**Comment by michaelangrivera** [comment]
![Screen Shot 2022-07-03 at 1 13 12 PM](https://user-images.githubusercontent.com/55844504/177050263-cf13c8d2-cb2b-432d-95b9-b5cb20a916c2.png)
I would assume the background colors would apply with that configuration on the Next app, no? 
Or am I missing a provider/next specific configuration?

**Comment by nandorojo** [comment]
oh, no. the colors are just theme keys. to use them, do something like:

`<View sx={{ bg: ‘$background’ }} />`

**Comment by michaelangrivera** [comment]
Gotcha! Figured I was being dumb. I assumed it was similar to `mui` where you use a theme provider and the components inherit the theme. 

Thank you!

Mind if I make a dripsy/docs PR under the theming section? It's probably repetitive of https://www.dripsy.xyz/usage/overview, but maybe it would help if a user misses that section (like me 😬 )

**Comment by nandorojo** [comment]
go for it

**Comment by nandorojo** [comment]
(had me worried 😅)
